import type { AvdLineJSON } from '../../components';

export const HA11_LINES: AvdLineJSON[] = [
  { speaker: '', text: '戦争はパワルが勝利した。' },
  { speaker: '有理紗', bgKey: '1', text: '勝利おめでとうございます茶羅井様' },
  { speaker: '茶羅井', bgKey: '1', text: '有理紗も頑張ってくれたからだよ' },
  { speaker: '有理紗', bgKey: '1', text: 'ああんっ、茶羅井様褒めてくれてありがとうございます' },
  { speaker: '', bgKey: '1', text: 'セックスしながら勝利を祝い合う二人。' },
  { speaker: '茶羅井', bgKey: '1', text: '有理紗が俺の女になってくれて良かったよ' },
  { speaker: '有理紗', bgKey: '1', text: 'お礼を言うのは私の方です' },
  { speaker: '有理紗', bgKey: '1', text: '茶羅井様の女にしてもらえたから今こんなに幸せなんです！' },
  { speaker: '有理紗', bgKey: '1', text: 'もう茶羅井様のいない世界なんて考えられません！' },
  { speaker: '有理紗', bgKey: '1', text: '茶羅井様愛してます！一生離れません！！' },
  { speaker: '茶羅井', bgKey: '1', text: '(魅了の魔法は凄いな…' },
  { speaker: '茶羅井', bgKey: '1', text: ' 敵対していた女が一瞬でここまで依存するようになるんだもんな)' },
  { speaker: '有理紗', bgKey: '1', text: '茶羅井様気持ち良いですか？' },
  { speaker: '茶羅井', bgKey: '1', text: 'ああ、良いぞ' },
  { speaker: '有理紗', bgKey: '1', text: 'ああんっ、嬉しいです！' },
  { speaker: '有理紗', bgKey: '1', text: 'もっと気持ち良くなってください！' },
  { speaker: '茶羅井', bgKey: '1', text: 'ああ' },
  { speaker: '', bgKey: '2', text: '速度を上げる二人。' },
  { speaker: '茶羅井', bgKey: '2', text: 'ああ･･･イきそうだ、中に出すぞ！' },
  { speaker: '有理紗', bgKey: '2', text: 'はい！来てください！私の中を茶羅井様で満たしてください！' },
  { speaker: '', bgKey: '3', text: 'ドピュッドピュー' },
  { speaker: '有理紗', bgKey: '4', text: 'ああ･･･出てる･･･' },
  { speaker: '有理紗', bgKey: '4', text: '茶羅井様の精液が中に･･･嬉しいです！' },
  { speaker: '茶羅井', bgKey: '4', text: '気持ち良かったよ' },
  { speaker: '有理紗', bgKey: '4', text: 'ありがとうございます茶羅井様' },
  { speaker: '有理紗', bgKey: '4', text: '一生お側でお仕えいたします' },
  { speaker: '有理紗', bgKey: '5', text: 'んっ' },
  { speaker: '', bgKey: '5', text: 'キスをする二人。' },
  { speaker: '', bgKey: '5', text: 'こうして有理紗は茶羅井の女として過ごすのだった。' },
  { speaker: '', bgKey: '5', text: '茶羅井敗北エンド' },
  { speaker: '', text: '— HA11 终 —', end: true },
];

export const HA12_LINES: AvdLineJSON[] = [
  { speaker: '詩保', bgKey: '6', text: '身体が動かない…' },
  { speaker: '小茂田', bgKey: '6', text: 'デュフフ、詩保ちゃんようこそマシナ国へ' },
  { speaker: '詩保', bgKey: '6', text: 'その声、小茂田さん…？' },
  { speaker: '小茂田', bgKey: '6', text: 'そうだよ覚えててくれたんだ嬉しいなあ' },
  { speaker: '詩保', bgKey: '6', text: '私をどうする気ですか？' },
  { speaker: '小茂田', bgKey: '6', text: 'それはね…僕の言うこと何でも聞いてくれる' },
  { speaker: '小茂田', bgKey: '6', text: '理想の女の子になってもらうんだよ' },
  { speaker: '詩保', bgKey: '7', text: 'そんなのになるわけがありません！' },
  { speaker: '小茂田', bgKey: '7', text: 'そうだね･･･' },
  { speaker: '小茂田', bgKey: '7', text: '今のままだと僕のものになんて絶対になってくれないよね･･･' },
  { speaker: '小茂田', bgKey: '7', text: 'だから今付けている洗脳装置の出番ってわけさ' },
  { speaker: '詩保', bgKey: '8', text: '洗脳…装置…？' },
  { speaker: '小茂田', bgKey: '8', text: 'うん、僕の能力で作った機械の一つさ' },
  { speaker: '小茂田', bgKey: '8', text: 'これで詩保ちゃんを洗脳して僕の女にする！' },
  { speaker: '小茂田', bgKey: '8', text: 'ゆくゆくは有理紗ちゃんも僕の女にするつもりさ' },
  { speaker: '詩保', bgKey: '8', text: '人の心を無理やり書き換えるなんて、' },
  { speaker: '詩保', bgKey: '8', text: 'そんな非人道的な行為はやめてください！' },
  { speaker: '小茂田', bgKey: '8', text: '嫌だね、じゃあ始めるよ' },
  { speaker: '詩保', bgKey: '9', text: 'ああああああ頭が痛いいいいいいいい' },
  { speaker: '小茂田', bgKey: '9', text: '脳に電気でダメージを与えて、そこに僕の考えたデータを流し込む' },
  { speaker: '小茂田', bgKey: '9', text: 'そうすることで僕の理想データを' },
  { speaker: '小茂田', bgKey: '9', text: '植え付けていくことができるんだよ' },
  { speaker: '詩保', bgKey: '9', text: '痛いいいいい痛いですうううううう' },
  { speaker: '小茂田', bgKey: '9', text: 'あれ？全然洗脳が進まない…' },
  { speaker: '詩保', bgKey: '9', text: 'あががががががが' },
  { speaker: '小茂田', bgKey: '9', text: 'もしかして抵抗している？' },
  { speaker: '小茂田', bgKey: '9', text: '確か詩保ちゃんの能力は回復だったよね･･･' },
  { speaker: '小茂田', bgKey: '9', text: 'まさか脳へのダメージも即座に回復している！？' },
  { speaker: '詩保', bgKey: '10', text: '私は…あなたのものになんかならないいいいいいい' },
  { speaker: '小茂田', bgKey: '10', text: 'ああそうかよ！そこまで僕のものになりたくないのかよ！！' },
  { speaker: '', bgKey: '11', text: '洗脳装置が停止する。' },
  { speaker: '詩保', bgKey: '11', text: 'はあ…はあ…わかってくれたのですか…？' },
  { speaker: '小茂田', bgKey: '11', text: 'もういいよ、君の心は諦めるよ' },
  { speaker: '小茂田', bgKey: '11', text: '身体だけ使わせてもらうから' },
  { speaker: '詩保', bgKey: '11', text: '何を言って…' },
  { speaker: '', bgKey: '12', text: '詩保に付けられている装置のバイザーが再び起動する。' },
  { speaker: '詩保', bgKey: '12', text: '次は何ですか！？' },
  { speaker: '', bgKey: '14', text: '拘束が解除される。' },
  { speaker: '詩保', bgKey: '14', text: 'どうして･･･身体が動かないです…' },
  { speaker: '小茂田', bgKey: '14', text: 'そのバイザーから特殊な電気信号を送ってるんだよ' },
  { speaker: '小茂田', bgKey: '14', text: '今の詩保ちゃんはそのバイザーからの指示でしか' },
  { speaker: '小茂田', bgKey: '14', text: '身体を動かせないんだ' },
  { speaker: '詩保', bgKey: '14', text: 'そんな…そんなことがあるわけ…' },
  { speaker: '小茂田', bgKey: '14', text: 'じゃあほら' },
  { speaker: '詩保', bgKey: '15', text: 'えっ、手が勝手に' },
  { speaker: '', bgKey: '15', text: '詩保の手が勝手に胸へと向かう。' },
  { speaker: '詩保', bgKey: '15', text: 'きゃああ、何をさせるのですか！？' },
  { speaker: '小茂田', bgKey: '15', text: 'ほら、左手も' },
  { speaker: '詩保', bgKey: '16', text: 'いやああ手が勝手にいいいい' },
  { speaker: '小茂田', bgKey: '16', text: 'いいねいいね、エッチだよ' },
  { speaker: '', bgKey: '17', text: 'その姿はオナニーをしているようにしか見えなかった。' },
  { speaker: '詩保', bgKey: '17', text: 'お願いです、こんなことやめてください' },
  { speaker: '小茂田', bgKey: '17', text: 'ダメだよ' },
  { speaker: '小茂田', bgKey: '17', text: '僕の洗脳を拒んだことを後悔させてあげる' },
  { speaker: '小茂田', bgKey: '17', text: 'イクまで…' },
  { speaker: '小茂田', bgKey: '17', text: 'いや、イッても僕が良いと言うまでオナニーを続けるんだ' },
  { speaker: '詩保', bgKey: '18', text: 'いやあああああ、お願いです、やめてください！！' },
  { speaker: '詩保', bgKey: '18', text: 'ああんっ、手が勝手にぃ' },
  { speaker: '詩保', bgKey: '18', text: 'でも、こんな無理やりやらされて気持ち良くなんてならないです！' },
  { speaker: '小茂田', bgKey: '18', text: 'そっか･･･でも僕が命令すればすぐにイクと思うよ' },
  { speaker: '小茂田', bgKey: '18', text: 'ほらイケ！' },
  { speaker: '', bgKey: '19', text: '絶頂してしまう詩保。' },
  { speaker: '詩保', bgKey: '20', text: 'そんなぁ、どうして私…' },
  { speaker: '小茂田', bgKey: '20', text: '詩保ちゃんの身体は僕が支配しているんだよ' },
  { speaker: '小茂田', bgKey: '20', text: '絶頂すらもね' },
  { speaker: '詩保', bgKey: '20', text: '嘘でしょ･･･' },
  { speaker: '詩保', bgKey: '21', text: 'ああんっ' },
  { speaker: '詩保', bgKey: '21', text: 'イッたから、休ませてぇ' },
  { speaker: '', bgKey: '21', text: '絶頂しようがお構いなしに詩保の手は動き続ける。' },
  { speaker: '小茂田', bgKey: '21', text: 'こんなんじゃ済まさないよ' },
  { speaker: '小茂田', bgKey: '21', text: 'エッチなことだけじゃない、' },
  { speaker: '小茂田', bgKey: '21', text: '君がきっと嫌がるであろうこと、いっぱいさせてあげるからね' },
  { speaker: '詩保', bgKey: '13', text: 'いやぁ…もう許してください…' },
  { speaker: '詩保', bgKey: '13', text: '(有理紗さん…助けて…)' },
  { speaker: '', text: '— HA12 终 —', end: true },
];

export const HB11_LINES: AvdLineJSON[] = [
  { speaker: '詩保', bgKey: '22', text: 'ああああ小茂田様あああああやっと私を消してもらえるううううう' },
  { speaker: '有理紗', bgKey: '31', text: 'お願い詩保、こんな奴の洗脳なんて受け入れないで！' },
  { speaker: '詩保', bgKey: '31', text: 'いやですうううう、小茂田様のものになりたいですう' },
  { speaker: '詩保', bgKey: '31', text: '小茂田様！小茂田様あああ！！！早く私を消してくださいいいい！' },
  { speaker: '', bgKey: '31', text: '詩保の装置の電気が強くなる。' },
  { speaker: '詩保', bgKey: '37', text: 'あひいいいいい小茂田様ああああああああああああああ' },
  { speaker: '有理紗', bgKey: '37', text: '詩保！詩保おおおおお' },
  { speaker: '詩保', bgKey: '38', text: 'はあはあ' },
  { speaker: '', bgKey: '39', text: '詩保の装置が取り外される。' },
  { speaker: '詩保', bgKey: '39', text: '小茂田様、洗脳していただきありがとうございます' },
  { speaker: '詩保', bgKey: '39', text: '小茂田様のためならどんなことでもできそうです' },
  { speaker: '詩保', bgKey: '39', text: '人殺しだってなんとも思わないです' },
  { speaker: '小茂田', bgKey: '39', text: 'でゅふふ、良かったね詩保ちゃん、いや詩保' },
  { speaker: '詩保', bgKey: '40', text: '有理紗さんも小茂田様のものになりましょう' },
  { speaker: '詩保', bgKey: '40', text: 'とーっても幸せな気持ちになれますよー' },
  { speaker: '有理紗', bgKey: '41', text: 'いやああああ、私は絶対小茂田のものになんかならない！！' },
  { speaker: '有理紗', bgKey: '42', text: 'ぎゃああああああああああ痛い痛いいいいい' },
  { speaker: '', bgKey: '42', text: '小茂田様小茂田様小茂田様小茂田様小茂田様小茂田様小茂田様' },
  { speaker: '', bgKey: '42', text: '小茂田様小茂田様小茂田様小茂田様小茂田様小茂田様小茂田様' },
  { speaker: '', bgKey: '42', text: '小茂田様小茂田様小茂田様小茂田様小茂田様小茂田様小茂田様' },
  { speaker: '', bgKey: '42', text: '小茂田様小茂田様小茂田様小茂田様小茂田様小茂田様小茂田様' },
  { speaker: '有理紗', bgKey: '42', text: 'いやああああ、私の中に入ってこないでええええええ' },
  { speaker: '有理紗', bgKey: '42', text: '小茂田様が私の中に入って来るのおおおおおお' },
  { speaker: '有理紗', bgKey: '42', text: 'やめてーーー！！！出て行ってーーーーー' },
  { speaker: '有理紗', bgKey: '43', text: '(小茂田『様』？あれ、どうして私様付けなんて…？)' },
  { speaker: '', bgKey: '43', text: '小茂田様小茂田様小茂田様小茂田様小茂田様小茂田様小茂田様' },
  { speaker: '有理紗', bgKey: '43', text: '(小茂田様って呼ぶのは普通のこと…だよね……)' },
  { speaker: '有理紗', bgKey: '23', text: 'あひいいいいいいい' },
  { speaker: '有理紗', bgKey: '23', text: '(いくら小茂田様でも洗脳されるのは嫌あああああ)' },
  { speaker: '有理紗', bgKey: '23', text: 'お願いです小茂田様、洗脳しないでくださいいいいい' },
  { speaker: '小茂田', bgKey: '23', text: 'どうして僕に洗脳されるのが嫌なの？' },
  { speaker: '有理紗', bgKey: '23', text: 'それはああああ…' },
  { speaker: '有理紗', bgKey: '23', text: '(あれ？言われてみれば･･･' },
  { speaker: '有理紗', bgKey: '23', text: ' どうして小茂田様に洗脳されるの嫌なんだろう…)' },
  { speaker: '詩保', bgKey: '24', text: '有理紗さんも早く小茂田様のものになりましょうよ' },
  { speaker: '有理紗', bgKey: '24', text: '(この声詩保？' },
  { speaker: '有理紗', bgKey: '24', text: ' そういえば詩保は自分から洗脳してもらってたっけ…)' },
  { speaker: '詩保', bgKey: '24', text: '小茂田様に洗脳されるのって凄く気持ち良いですよね' },
  { speaker: '詩保', bgKey: '24', text: 'そうは思いませんか？' },
  { speaker: '有理紗', bgKey: '25', text: '(確かに言われてみれば頭を流れてる電気･･･気持ち良いかも…)' },
  { speaker: '有理紗', bgKey: '25', text: 'そう…かも…' },
  { speaker: '詩保', bgKey: '27', text: 'そうですよね！もっと気持ち良くなりたいですよね！' },
  { speaker: '有理紗', bgKey: '27', text: '(もしかして洗脳って気持ち良いことなの…？' },
  { speaker: '有理紗', bgKey: '27', text: ' だったら拒絶することもないのかも…)' },
  { speaker: '有理紗', bgKey: '27', text: 'もっと気持ち良くなりたい…' },
  { speaker: '小茂田', bgKey: '27', text: 'おっ、一気に洗脳が進んだね' },
  { speaker: '小茂田', bgKey: '27', text: '詩保の声は効果絶大みたいだね' },
  { speaker: '詩保', bgKey: '26', text: '本当ですか？小茂田様の役に立ててるなら嬉しいです' },
  { speaker: '小茂田', bgKey: '26', text: 'そのままもっと僕のものになりたくなるようなことを' },
  { speaker: '小茂田', bgKey: '26', text: '有理紗に言ってよ' },
  { speaker: '詩保', bgKey: '26', text: 'わかりました' },
  { speaker: '詩保', bgKey: '27', text: '有理紗さん、もっと気持ち良くなりたいですよね？' },
  { speaker: '有理紗', bgKey: '27', text: 'なりたい…' },
  { speaker: '詩保', bgKey: '27', text: 'だったら、小茂田様に忠誠を誓うと良いですよ' },
  { speaker: '有理紗', bgKey: '27', text: '小茂田様に…？' },
  { speaker: '詩保', bgKey: '27', text: 'はい' },
  { speaker: '詩保', bgKey: '27', text: '小茂田様に忠誠を誓う行為はこの世で一番気持ちの良い行為ですよ' },
  { speaker: '有理紗', bgKey: '27', text: '(小茂田様って…見た目が悪くて…)' },
  { speaker: '', bgKey: '28', text: '小茂田様はイケメン' },
  { speaker: '有理紗', bgKey: '28', text: '(いや私の理想の見た目だったっけ･･･)' },
  { speaker: '有理紗', bgKey: '28', text: '(でも性格はキモそうで…)' },
  { speaker: '', bgKey: '28', text: '小茂田様は性格も優しくて素敵な人' },
  { speaker: '有理紗', bgKey: '29', text: '(すごく優しそうで…あれ？拒む理由なんて一つもないじゃない…)' },
  { speaker: '有理紗', bgKey: '29', text: '(どうして拒もうとしていたんだろう…)' },
  { speaker: '有理紗', bgKey: '29', text: '誓います…' },
  { speaker: '小茂田', bgKey: '29', text: 'ん？なんだって？' },
  { speaker: '有理紗', bgKey: '30', text: '小茂田様に忠誠を誓います！！！' },
  { speaker: '有理紗', bgKey: '32', text: 'おほおおおおおおおおおおおおお気持ち良いいいいい' },
  { speaker: '', bgKey: '33', text: '宣言と同時に電気が流れ、絶頂する有理紗。' },
  { speaker: '小茂田', bgKey: '34', text: 'これで有理紗は僕への忠誠心が完全に固定されたね' },
  { speaker: '', bgKey: '35', text: '装置が外される。' },
  { speaker: '小茂田', bgKey: '35', text: 'さて、二人とも僕に洗脳されてどんな気分だい？' },
  { speaker: '有理紗', bgKey: '36', text: 'はいぃ最高の気分ですぅ' },
  { speaker: '詩保', bgKey: '36', text: '私も幸せな気持ちでいっぱいです' },
  { speaker: '', bgKey: '36', text: '洗脳により書き換えられた認識を持ったまま二人の目に光が戻る。' },
  { speaker: '', bgKey: '36', text: 'それは小茂田の洗脳が完了したことを意味していた。' },
  { speaker: '', bgKey: '36', text: '彼女たちは正気でありながら' },
  { speaker: '', bgKey: '36', text: '小茂田に忠誠を誓う存在になってしまったのだ。' },
  { speaker: '', bgKey: '36', text: '有理紗と詩保は立ち上がり小茂田の前に並ぶ。' },
  { speaker: '小茂田', bgKey: '44', text: 'それじゃあ、忠誠の証を見せてもらおうかな' },
  { speaker: '小茂田', bgKey: '44', text: 'もちろんわかるよね？' },
  { speaker: '詩保', bgKey: '45', text: '小茂田様の忠実なるメス奴隷の詩保です！' },
  { speaker: '', bgKey: '45', text: 'そう言いスカートをたくし上げパンツを見せる詩保。' },
  { speaker: '有理紗', bgKey: '46', text: '私も小茂田様の忠実なるメス奴隷です！' },
  { speaker: '', bgKey: '46', text: '詩保に続き有理紗もスカートをたくし上げる。' },
  { speaker: '小茂田', bgKey: '46', text: 'いいねいいね、最高だよ！！' },
  { speaker: '', bgKey: '46', text: '『忠誠を誓う時にはパンツを見せること』と洗脳していた小茂田。' },
  { speaker: '', bgKey: '46', text: '二人の美少女がパンツを見せている光景に興奮を隠せなかった。' },
  { speaker: '有理紗＆詩保', bgKey: '47', text: '小茂田様に忠誠を誓います！' },
  { speaker: '', text: '— HB11 终 —', end: true },
];

export const HB12_LINES: AvdLineJSON[] = [
  { speaker: '小茂田', bgKey: '48', text: '二人ともよく来たね' },
  { speaker: '有理紗＆詩保', bgKey: '49', text: '小茂田様、今日も私たちといっぱいエッチなことしてください' },
  { speaker: '', bgKey: '49', text: '一切の恥じらいもなく平然とスカートをたくし上げる二人。' },
  { speaker: '', bgKey: '49', text: 'パンツを見せて小茂田への忠誠を現す行為は、' },
  { speaker: '', bgKey: '49', text: '二人にとって当たり前のこととなっていた。' },
  { speaker: '小茂田', bgKey: '49', text: 'デュフフもちろん！いっぱいエッチしようね' },
  { speaker: '小茂田', bgKey: '49', text: '(何度見ても最高の眺めだな)' },
  { speaker: '', bgKey: '49', text: '本来であれば一生関わることのできないであろう美少女二人が' },
  { speaker: '', bgKey: '49', text: '自分に忠誠を誓う姿は何度見ても興奮するものであった。' },
  { speaker: '小茂田', bgKey: '50', text: 'そうだ、今日はこれを着て欲しいな' },
  { speaker: '', bgKey: '50', text: 'そう言い小茂田が取り出してきたのはメイド服だった。' },
  { speaker: '有理紗', bgKey: '50', text: 'わかりました、今からここで着替えますね' },
  { speaker: '詩保', bgKey: '50', text: '私も小茂田様に着替えを見てもらいたいです' },
  { speaker: '詩保', bgKey: '50', text: '私のことも見てくださいね' },
  { speaker: '小茂田', bgKey: '50', text: 'もちろんだよ' },
  { speaker: '小茂田', bgKey: '50', text: '二人ともしっかり見てあげるからね' },
  { speaker: '', bgKey: '51', text: '小茂田の前でも躊躇いなく服を脱ぐ二人。' },
  { speaker: '', bgKey: '51', text: 'それどころか、小茂田に見られていることに嬉しさを感じている。' },
  { speaker: '有理紗', bgKey: '51', text: '(小茂田様が私のこと見てる･･･' },
  { speaker: '有理紗', bgKey: '51', text: ' 嬉しい･･･もっと私のこと見て欲しいな･･･)' },
  { speaker: '詩保', bgKey: '51', text: '(小茂田様･･･私のこともっと見て欲しいです' },
  { speaker: '詩保', bgKey: '51', text: ' できれば私のことだけ見て欲しいです･･･)' },
  { speaker: '有理紗', bgKey: '54', text: '着替えました小茂田様' },
  { speaker: '詩保', bgKey: '54', text: '私も着替え終わりました、小茂田様' },
  { speaker: '小茂田', bgKey: '54', text: 'うんうん、二人ともよく似合ってるよ！' },
  { speaker: '小茂田', bgKey: '54', text: 'でもせっかくのメイド服なんだ' },
  { speaker: '小茂田', bgKey: '54', text: '今日は僕のことを『ご主人様』って呼んでほしいな' },
  { speaker: '有理紗＆詩保', bgKey: '54', text: 'わかりましたご主人様' },
  { speaker: '詩保', bgKey: '55', text: 'さあご主人様、早く私たちにエッチなことしてください' },
  { speaker: '小茂田', bgKey: '55', text: '本当にエッチなメイドたちだなあ、ほらおいで' },
  { speaker: '', bgKey: '56', text: 'そう言いペニスを出す小茂田。' },
  { speaker: '有理紗＆詩保', bgKey: '56', text: 'ご主人様のおチンポ！！' },
  { speaker: '', bgKey: '57', text: '飛びかかる勢いでペニスに食らいつこうとする二人。' },
  { speaker: '有理紗', bgKey: '67', text: '私が奉仕します！' },
  { speaker: '詩保', bgKey: '67', text: '待ってください、私がご奉仕します！！' },
  { speaker: '', bgKey: '67', text: 'ペニスの取り合いになる。' },
  { speaker: '小茂田', bgKey: '67', text: 'こらこら喧嘩しないで、順番にね' },
  { speaker: '小茂田', bgKey: '67', text: 'まずは有理紗から' },
  { speaker: '有理紗', bgKey: '68', text: 'やった！' },
  { speaker: '詩保', bgKey: '68', text: 'そんなあ' },
  { speaker: '小茂田', bgKey: '68', text: 'がっかりしないで、ちゃんと詩保にもしゃぶらせてあげるから' },
  { speaker: '有理紗', bgKey: '68', text: 'それでは失礼いたします' },
  { speaker: '', bgKey: '69', text: 'そう言い小茂田のペニス咥える有理紗。' },
  { speaker: '有理紗', bgKey: '69', text: '(ご主人様のおチンポ……美味しい……)' },
  { speaker: '', bgKey: '69', text: '小茂田のペニスに夢中になる有理紗。' },
  { speaker: '小茂田', bgKey: '69', text: 'ああ良いよぉ有理紗' },
  { speaker: '有理紗', bgKey: '69', text: 'ありがとうございます' },
  { speaker: '', bgKey: '70', text: 'さらに激しく動く有理紗。' },
  { speaker: '小茂田', bgKey: '70', text: 'ああ気持ち良いよ…' },
  { speaker: '小茂田', bgKey: '70', text: 'ダメだ出ちゃいそうだからストップ！' },
  { speaker: '有理紗', bgKey: '71', text: 'そんなぁ…' },
  { speaker: '小茂田', bgKey: '71', text: '詩保にもしゃぶらせてあげないと、ほら詩保しゃぶって良いよ' },
  { speaker: '詩保', bgKey: '71', text: 'はいご主人様' },
  { speaker: '', bgKey: '72', text: '次は詩保が小茂田のペニスを咥える。' },
  { speaker: '', bgKey: '73', text: 'ジュッポジュッポと音を立て小茂田のペニスに奉仕する詩保。' },
  { speaker: '小茂田', bgKey: '73', text: 'ずいぶんとエッチになったね詩保は' },
  { speaker: '小茂田', bgKey: '73', text: 'あんなに清楚だったのに' },
  { speaker: '詩保', bgKey: '73', text: 'ふぃふぁでひゅか？(嫌ですか？)' },
  { speaker: '', bgKey: '73', text: 'しゃぶりながら質問する詩保。' },
  { speaker: '小茂田', bgKey: '73', text: 'そんなわけないよ' },
  { speaker: '小茂田', bgKey: '73', text: 'エッチな詩保も大好きだよ' },
  { speaker: '詩保', bgKey: '73', text: 'うれふぃいでひゅごひゅじんひゃま(嬉しいですご主人様)' },
  { speaker: '有理紗', bgKey: '74', text: 'ご主人様！私にも好きって言ってください！' },
  { speaker: '', bgKey: '74', text: '詩保に好きと言っていたことで嫉妬する有理紗。' },
  { speaker: '小茂田', bgKey: '74', text: 'もちろん有理紗のことも好きだよ' },
  { speaker: '小茂田', bgKey: '74', text: '僕は君たち二人のことを愛してるからね' },
  { speaker: '有理紗', bgKey: '58', text: 'ご主人様♡' },
  { speaker: '', bgKey: '58', text: 'うっとりする有理紗。' },
  { speaker: '', bgKey: '58', text: '愛の言葉を聞いて詩保のフェラも激しくなる。' },
  { speaker: '小茂田', bgKey: '58', text: 'ああ、詩保ストップ！' },
  { speaker: '詩保', bgKey: '59', text: 'ご主人様、どうして止めないといけないのですか？' },
  { speaker: '小茂田', bgKey: '60', text: '最後は二人に舐めて欲しいからさ' },
  { speaker: '詩保', bgKey: '61', text: 'そうなのですね' },
  { speaker: '詩保', bgKey: '61', text: 'じゃあ有理紗さん二人でご主人様のことをイカせてあげましょう' },
  { speaker: '有理紗', bgKey: '61', text: 'わかったわ詩保' },
  { speaker: '有理紗', bgKey: '61', text: 'それじゃあご主人様、二人でご奉仕しますね' },
  { speaker: '', bgKey: '62', text: '二人で小茂田のペニスを舐め始める。' },
  { speaker: '小茂田', bgKey: '62', text: '二人とも本当に上手になったね、もう出ちゃいそうだよ' },
  { speaker: '有理紗', bgKey: '62', text: 'ご主人様、いつでも出して良いですからね' },
  { speaker: '詩保', bgKey: '62', text: 'そうですよ、早く私たちにいっぱいかけてください' },
  { speaker: '小茂田', bgKey: '62', text: 'ああ、出るよ！' },
  { speaker: '', bgKey: '63', text: 'ドピュッ！！ドピュッ！！ドピュッ！！ ' },
  { speaker: '', bgKey: '63', text: '大量の精液が有理紗と詩保に降りかかる。' },
  { speaker: '有理紗', bgKey: '64', text: '(ああ熱い……ご主人様の精液……)' },
  { speaker: '詩保', bgKey: '64', text: '(ご主人様の精液がこんなに……)' },
  { speaker: '', bgKey: '64', text: '恍惚とした表情で精液を浴びる二人。' },
  { speaker: '小茂田', bgKey: '64', text: 'さて、じゃあ次はセックスだね。' },
  { speaker: '小茂田', bgKey: '64', text: '今日の相手はどっちにしようかな…' },
  { speaker: '小茂田', bgKey: '64', text: 'じゃあ、今日は有理紗！' },
  { speaker: '有理紗', bgKey: '65', text: 'やった！！' },
  { speaker: '詩保', bgKey: '65', text: 'そんなあ…' },
  { speaker: '小茂田', bgKey: '65', text: 'じゃあ、今日は詩保！' },
  { speaker: '詩保', bgKey: '66', text: 'はい！' },
  { speaker: '有理紗', bgKey: '66', text: 'そんなぁ…' },
  { speaker: '', text: '— HB12 终 —', end: true },
];

export const T1_LINES: AvdLineJSON[] = [
  { speaker: '有理紗', bgKey: '75', text: 'ああん、ご主人様のが入って来るぅ' },
  { speaker: '小茂田', bgKey: '75', text: 'どうだい有理紗？気持ち良いかい？' },
  { speaker: '有理紗', bgKey: '75', text: 'はい、最高ですご主人様！' },
  { speaker: '小茂田', bgKey: '75', text: 'ほら詩保も' },
  { speaker: '詩保', bgKey: '76', text: 'ああんっ、ご主人様ぁ･･･' },
  { speaker: '有理紗', bgKey: '77', text: 'ご主人様も気持ち良くなってください！' },
  { speaker: '', bgKey: '77', text: 'そう言い腰を動かす有理紗。' },
  { speaker: '有理紗', bgKey: '77', text: '(ああ、やっぱりご主人様とのセックスの時間最高･･･)' },
  { speaker: '詩保', bgKey: '77', text: '(有理紗さん羨ましい･･･' },
  { speaker: '詩保', bgKey: '77', text: ' 私もご主人様のおチンチン欲しいです･･･)' },
  { speaker: '詩保', bgKey: '78', text: 'んっ' },
  { speaker: '詩保', bgKey: '78', text: '(でもこうしてご主人様に触ってもらいながら' },
  { speaker: '詩保', bgKey: '78', text: ' キスするのも悪くはないですね)' },
  { speaker: '', bgKey: '78', text: '詩保は詩保で気持ち良くなっている。' },
  { speaker: '小茂田', bgKey: '79', text: 'そろそろイクよ、有理紗！' },
  { speaker: '有理紗', bgKey: '79', text: '私もイキますうううう' },
  { speaker: '詩保', bgKey: '79', text: '私も･･･' },
  { speaker: '', bgKey: '80', text: '揃って絶頂する。' },
  { speaker: '小茂田', bgKey: '81', text: 'ふう…気持ち良かったよ' },
  { speaker: '有理紗', bgKey: '81', text: 'ありがとうございますご主人様' },
  { speaker: '小茂田', bgKey: '81', text: 'これからも僕の女でいてくれるかい？' },
  { speaker: '有理紗＆詩保', bgKey: '81', text: 'はい！もちろんですご主人様♡' },
  { speaker: '', bgKey: '81', text: 'こうして二人は小茂田の奴隷として一生を過ごすことになる。' },
  { speaker: '', bgKey: '81', text: '小茂田エンド' },
  { speaker: '', text: '— T1 终 —', end: true },
];

export const T2_LINES: AvdLineJSON[] = [
  { speaker: '詩保', bgKey: '82', text: 'ああん、ご主人様のが入って来ますぅ' },
  { speaker: '小茂田', bgKey: '82', text: 'どうだい詩保？気持ち良いかい？' },
  { speaker: '詩保', bgKey: '82', text: 'はい、とても気持ち良いですご主人様！' },
  { speaker: '小茂田', bgKey: '82', text: '僕も気持ち良いよ詩保' },
  { speaker: '小茂田', bgKey: '82', text: 'ほら有理紗も' },
  { speaker: '有理紗', bgKey: '83', text: 'あんっ、ご主人様ぁ･･･' },
  { speaker: '', bgKey: '84', text: '詩保が腰を動かしパンッパンッと激しい音が聞こえる。' },
  { speaker: '詩保', bgKey: '84', text: '(ご主人様とセックスしている時間…幸せです…)' },
  { speaker: '有理紗', bgKey: '84', text: '(私もご主人様のおチンポ欲しいなあ……)' },
  { speaker: '有理紗', bgKey: '85', text: 'んっ' },
  { speaker: '有理紗', bgKey: '85', text: '(ご主人様とキスできるから、これも悪くないわね)' },
  { speaker: '', bgKey: '85', text: '有理紗も小茂田に手マンされて気持ち良くなっていた。' },
  { speaker: '詩保', bgKey: '86', text: 'ああご主人様、もうイキそうです！！' },
  { speaker: '小茂田', bgKey: '86', text: '僕も出そうだよ、一緒にイこう！' },
  { speaker: '有理紗', bgKey: '86', text: '私もイッちゃいそうです' },
  { speaker: '', bgKey: '87', text: '揃って絶頂する。' },
  { speaker: '小茂田', bgKey: '88', text: 'ふう…気持ち良かったよ' },
  { speaker: '詩保', bgKey: '88', text: 'ありがとうございますご主人様' },
  { speaker: '小茂田', bgKey: '88', text: 'これからも僕の女でいてくれるかい？' },
  { speaker: '有理紗＆詩保', bgKey: '88', text: 'はい！もちろんですご主人様♡' },
  { speaker: '', bgKey: '88', text: 'こうして二人は小茂田の奴隷として一生を過ごすことになる。' },
  { speaker: '', bgKey: '88', text: '小茂田エンド' },
  { speaker: '', text: '— T2 终 —', end: true },
];

export const HA21_LINES: AvdLineJSON[] = [
  { speaker: '有理紗', bgKey: '89', text: '来てください教皇様' },
  { speaker: '', bgKey: '89', text: 'パンツを脱ぎベッドに横になる有理紗。' },
  { speaker: '教皇マルクス', bgKey: '89', text: 'では有理紗さん、入れますよ' },
  { speaker: '', bgKey: '91', text: '教皇のペニスが有理紗の中に挿入される。' },
  { speaker: '有理紗', bgKey: '91', text: '痛っ…' },
  { speaker: '', bgKey: '91', text: '初めての痛みに思わず声が出る。' },
  { speaker: '教皇マルクス', bgKey: '91', text: '初めてでしたか…でしたら' },
  { speaker: '教皇マルクス', bgKey: '92', text: 'ほら痛くないでしょう' },
  { speaker: '', bgKey: '92', text: '教皇が魔法を使うと、途端に痛みが消える。' },
  { speaker: '有理紗', bgKey: '92', text: '凄い、痛みが消えました･･･' },
  { speaker: '有理紗', bgKey: '92', text: 'なんていう奇跡の力･･･' },
  { speaker: '有理紗', bgKey: '93', text: '教皇様はまるで神様のようです' },
  { speaker: '教皇マルクス', bgKey: '93', text: 'そうですよ' },
  { speaker: '教皇マルクス', bgKey: '93', text: '私はいずれ神になる人ですのでこんなこともできるのですよ' },
  { speaker: '', bgKey: '93', text: '本当は洗脳魔法で痛みを感じないようにしているだけだが、' },
  { speaker: '', bgKey: '93', text: '有理紗には奇跡のように思えている。' },
  { speaker: '有理紗', bgKey: '93', text: 'すごいです教皇様' },
  { speaker: '有理紗', bgKey: '93', text: 'こんな人とセックスできるなんて感激です' },
  { speaker: '教皇マルクス', bgKey: '93', text: 'そうでしょう' },
  { speaker: '教皇マルクス', bgKey: '93', text: 'もっと感激するといいですよ' },
  { speaker: '教皇マルクス', bgKey: '93', text: 'さあ続けますよ' },
  { speaker: '有理紗', bgKey: '93', text: 'はい教皇様' },
  { speaker: '', bgKey: '94', text: '動き出す教皇。' },
  { speaker: '有理紗', bgKey: '94', text: 'ああんっ、教皇様気持ち良いです！' },
  { speaker: '有理紗', bgKey: '94', text: 'セックスってこんなに気持ち良い物だったのですね！' },
  { speaker: '教皇マルクス', bgKey: '94', text: '気持ち良くなってもらえて私も嬉しいですよ' },
  { speaker: '教皇マルクス', bgKey: '94', text: 'ほらほらもっと激しくしますよ' },
  { speaker: '', bgKey: '95', text: 'さらに動きが激しくなる教皇。' },
  { speaker: '有理紗', bgKey: '95', text: 'すごいいいいい、教皇様凄すぎますううう' },
  { speaker: '有理紗', bgKey: '95', text: '気持ち良過ぎておかしくなっちゃいますうううう' },
  { speaker: '', bgKey: '95', text: '洗脳魔法で快楽も増幅されているため、' },
  { speaker: '', bgKey: '95', text: '教皇とのセックスは一度経験すると' },
  { speaker: '', bgKey: '95', text: '二度と抜け出せないレベルの快楽になっている。' },
  { speaker: '教皇マルクス', bgKey: '95', text: 'おかしくなって良いのですよ' },
  { speaker: '教皇マルクス', bgKey: '95', text: '存分に感じてください' },
  { speaker: '有理紗', bgKey: '95', text: 'はいぃ教皇しゃまあ、教皇しゃまああああ' },
  { speaker: '教皇マルクス', bgKey: '95', text: '快楽で頭も回らなくなってきているようですね' },
  { speaker: '教皇マルクス', bgKey: '95', text: 'ではそろそろ出しますよ' },
  { speaker: '有理紗', bgKey: '95', text: '出してください！教皇様の精液、私の中に出してくださいいいい！' },
  { speaker: '', bgKey: '96', text: 'そして有理紗の中に精液が注がれる。' },
  { speaker: '', bgKey: '97', text: 'その瞬間、有理紗の頭の中に快楽と幸福感が流れ込んでくる。' },
  { speaker: '有理紗', bgKey: '97', text: '(凄いいいい、セックス気持ち良すぎるうううう……)' },
  { speaker: '', bgKey: '98', text: '幸福感に酔いしれながら絶頂する有理紗。' },
  { speaker: '有理紗', bgKey: '90', text: 'あへえ･･･教皇しゃまあ･･･' },
  { speaker: '', bgKey: '90', text: 'こうして有理紗も教皇のものになるのだった…' },
  { speaker: '', text: '— HA21 终 —', end: true },
];

export const HA22_LINES: AvdLineJSON[] = [
  { speaker: '', text: 'セイレア教は世界を支配した。' },
  { speaker: '教皇マルクス', bgKey: '99', text: 'よくやりました、あなた達のおかげです' },
  { speaker: '', bgKey: '99', text: 'そこには教皇のペニスに奉仕する二人の女性がいた。' },
  { speaker: '有理紗', bgKey: '100', text: '私たちはただ教皇様の命令に従っただけです' },
  { speaker: '詩保', bgKey: '100', text: 'そうです、全て教皇様のお力です' },
  { speaker: '教皇マルクス', bgKey: '101', text: 'そうですか' },
  { speaker: '教皇マルクス', bgKey: '101', text: 'あなた達は本当に優秀な私の人形ですね' },
  { speaker: '有理紗', bgKey: '101', text: '教皇様に従うことが私の全てですから' },
  { speaker: '詩保', bgKey: '101', text: 'その通りです' },
  { speaker: '詩保', bgKey: '101', text: '教皇様に従うことこそが幸福なのですから' },
  { speaker: '教皇マルクス', bgKey: '101', text: '素晴らしい忠誠心です！' },
  { speaker: '教皇マルクス', bgKey: '101', text: 'ではたくさんかけてあげますからね' },
  { speaker: '', bgKey: '102', text: '教皇は二人の顔に精液をかける。' },
  { speaker: '詩保', bgKey: '103', text: 'ああこんなにたくさん…ありがとうございます教皇様' },
  { speaker: '有理紗', bgKey: '103', text: '私も心から感謝しています' },
  { speaker: '教皇マルクス', bgKey: '103', text: 'これからも私のために働いてもらいますよ' },
  { speaker: '有理紗＆詩保', bgKey: '104', text: 'はい教皇様' },
  { speaker: '', bgKey: '104', text: '詩保敗北エンド' },
  { speaker: '', text: '— HA22 终 —', end: true },
];

export const HA23_LINES: AvdLineJSON[] = [
  { speaker: '', text: '茶羅井は自室にセイレアを連れて行きベッドへ寝かせる。' },
  { speaker: '茶羅井', bgKey: '105', text: 'ほらセイレア、俺のものが欲しいんじゃないか？' },
  { speaker: '', bgKey: '105', text: 'ペニスを見せながらセイレアに問いかける。' },
  { speaker: 'セイレア', bgKey: '105', text: 'はいぃ、欲しいですぅ、茶羅井様のおチンポ欲しいですぅ' },
  { speaker: '茶羅井', bgKey: '105', text: 'そうかそんなに欲しいか' },
  { speaker: 'セイレア', bgKey: '105', text: 'はいぃ' },
  { speaker: 'セイレア', bgKey: '105', text: 'もう茶羅井様のおチンポが欲しくて欲しくてしょうがないんです' },
  { speaker: 'セイレア', bgKey: '105', text: '早く私のおマンコに茶羅井様のおチンポを入れてくださいぃ' },
  { speaker: '茶羅井', bgKey: '105', text: 'そこまで言われたらしょうがないな' },
  { speaker: '茶羅井', bgKey: '105', text: '入れてやるよ' },
  { speaker: 'セイレア', bgKey: '105', text: 'ありがとうございます茶羅井様' },
  { speaker: '', bgKey: '106', text: '茶羅井のペニスがセイレアの中に挿入される。' },
  { speaker: 'セイレア', bgKey: '106', text: 'ああっ、茶羅井様のが入って来る！！' },
  { speaker: '茶羅井', bgKey: '106', text: 'さすがに長い時間使われてないだけあってキツイな…' },
  { speaker: '茶羅井', bgKey: '106', text: 'だが、悪くない' },
  { speaker: '茶羅井', bgKey: '106', text: 'これから俺がいっぱい使ってほぐしてやるからな！' },
  { speaker: 'セイレア', bgKey: '107', text: 'はいっ、いっぱい使ってください！' },
  { speaker: 'セイレア', bgKey: '107', text: '女神の私も勇者の茶羅井様も死ぬことはないのです' },
  { speaker: 'セイレア', bgKey: '107', text: '永遠に使い続けてください！' },
  { speaker: '茶羅井', bgKey: '107', text: '永遠…かはわからないが飽きるまで使ってやるよ' },
  { speaker: 'セイレア', bgKey: '107', text: 'いやあ、捨てないでくださいいい' },
  { speaker: '茶羅井', bgKey: '107', text: 'じゃあ飽きないようにせいぜい頑張るんだな' },
  { speaker: 'セイレア', bgKey: '107', text: 'はい、茶羅井様を気持ち良くするために頑張ります' },
  { speaker: '茶羅井', bgKey: '107', text: 'じゃあその記念すべき最初のセックスを始めるぞ' },
  { speaker: '', bgKey: '108', text: 'そう言い腰を動かし始める茶羅井。' },
  { speaker: 'セイレア', bgKey: '108', text: 'ああっ！すごいです！！これがセックスなのですね！！' },
  { speaker: '茶羅井', bgKey: '108', text: 'そうだ！これがセックスだ！どうだ気持ちいいか？' },
  { speaker: 'セイレア', bgKey: '108', text: 'はい、とても気持ちいいです！' },
  { speaker: 'セイレア', bgKey: '108', text: '(人間はなぜセックスを頻繁にするのだろうと思っていましたが、' },
  { speaker: 'セイレア', bgKey: '108', text: ' こんなに良いものだったのですね…)' },
  { speaker: 'セイレア', bgKey: '109', text: '(こんなのハマるに決まっています！)' },
  { speaker: 'セイレア', bgKey: '109', text: '茶羅井様！もっと･･･もっと激しく動いてください！' },
  { speaker: '茶羅井', bgKey: '109', text: '言われなくてもそのつもりだ！！' },
  { speaker: '', bgKey: '110', text: '腰の動きをさらに激しくする茶羅井。' },
  { speaker: 'セイレア', bgKey: '110', text: 'ああっ、すごいです！！茶羅井様！' },
  { speaker: 'セイレア', bgKey: '110', text: '私を変えてくれてありがとうございます！！' },
  { speaker: 'セイレア', bgKey: '110', text: '以前の私はこんなに良いものを知らなかったなんて、' },
  { speaker: 'セイレア', bgKey: '110', text: '本当に愚かでした' },
  { speaker: '茶羅井', bgKey: '110', text: '魅了で無理やり好きにさせられているのに感謝してくれるのだな' },
  { speaker: 'セイレア', bgKey: '111', text: 'はい！本当に感謝しています！！' },
  { speaker: 'セイレア', bgKey: '111', text: 'ああ、先ほどの私はなんて愚かなことをしたのでしょう' },
  { speaker: 'セイレア', bgKey: '111', text: '私が力を飛ばさなければ' },
  { speaker: 'セイレア', bgKey: '111', text: '今頃茶羅井様はこの世界の支配者になっていたでしょうに' },
  { speaker: '茶羅井', bgKey: '111', text: 'それは愚かなことをしたな' },
  { speaker: 'セイレア', bgKey: '111', text: 'はい、本当に申し訳ありません' },
  { speaker: '茶羅井', bgKey: '111', text: 'じゃあ、その力を取り戻すために、俺と一緒に戦ってくれるか？' },
  { speaker: 'セイレア', bgKey: '111', text: 'はい！もちろんです' },
  { speaker: 'セイレア', bgKey: '111', text: '私は茶羅井様の奴隷なのですから、' },
  { speaker: 'セイレア', bgKey: '111', text: '命令されればどんなことでもします' },
  { speaker: 'セイレア', bgKey: '111', text: 'だから私にいっぱい命令してくださいいい' },
  { speaker: '茶羅井', bgKey: '111', text: 'いいぜ、じゃあ景気付けに一発出すぞ！' },
  { speaker: 'セイレア', bgKey: '111', text: 'はいぃ、出してください！' },
  { speaker: 'セイレア', bgKey: '111', text: '私の中にいっぱい出してくださいいい' },
  { speaker: '茶羅井', bgKey: '111', text: '出るっ！' },
  { speaker: '', bgKey: '112', text: 'セイレアの中に大量の精液を放出する茶羅井。' },
  { speaker: 'セイレア', bgKey: '113', text: 'ああっ、熱いですう･･･これが精液なのですね･･･' },
  { speaker: '茶羅井', bgKey: '113', text: 'ふう……気持ちよかったぜセイレア' },
  { speaker: 'セイレア', bgKey: '113', text: 'はい、私もとても気持ちよかったです……' },
  { speaker: '', text: '— HA23 终 —', end: true },
];

export const HA24_LINES: AvdLineJSON[] = [
  { speaker: '', text: '茶羅井は有理紗たちを自室に案内した。' },
  { speaker: '有理紗', bgKey: '114', text: 'どうぞ茶羅井様、私の初めてをもらってください' },
  { speaker: '茶羅井', bgKey: '114', text: 'おっ、処女なのか' },
  { speaker: '茶羅井', bgKey: '114', text: 'いいぜ最高の思い出にしてやるからな' },
  { speaker: '', bgKey: '115', text: '茶羅井のペニスが挿入される。' },
  { speaker: '有理紗', bgKey: '115', text: 'ああ、すごいです！！これがセックス･･･' },
  { speaker: '有理紗', bgKey: '115', text: '(ああ･･･茶羅井様とセックスしてる…なんて幸せなの！！)' },
  { speaker: '茶羅井', bgKey: '116', text: 'どうだ、気持ち良いか？' },
  { speaker: '有理紗', bgKey: '116', text: 'はい、とても気持ち良いです' },
  { speaker: '有理紗', bgKey: '116', text: 'もっとしてください！' },
  { speaker: '茶羅井', bgKey: '116', text: 'いいぜ、いっぱい突いてやるよ' },
  { speaker: '', bgKey: '117', text: '茶羅井の腰の動きが激しくなる。' },
  { speaker: '有理紗', bgKey: '117', text: 'ああ、すごいです！こんなの気持ち良すぎます！！' },
  { speaker: '有理紗', bgKey: '117', text: '(やばい･･･気持ち良すぎておかしくなりそう…)' },
  { speaker: '有理紗', bgKey: '117', text: '茶羅井様、茶羅井様ぁ！' },
  { speaker: '茶羅井', bgKey: '117', text: 'そろそろ出すぞ！' },
  { speaker: '有理紗', bgKey: '117', text: 'はい！中に出してください！' },
  { speaker: '', bgKey: '118', text: 'ドピュッビュルルルー' },
  { speaker: '', bgKey: '119', text: '茶羅井の精液が有理紗の中に放出される。' },
  { speaker: '有理紗', bgKey: '119', text: 'あぁ、熱い…' },
  { speaker: '茶羅井', bgKey: '119', text: 'ふう……気持ち良かったぜ' },
  { speaker: '有理紗', bgKey: '119', text: '私もすごく気持ちよかったです……' },
  { speaker: '有理紗', bgKey: '119', text: '(茶羅井様と一つになれて幸せ…)' },
  { speaker: '茶羅井', bgKey: '119', text: 'どうだ？俺の女になった感想は？' },
  { speaker: '有理紗', bgKey: '119', text: 'はい♡最高でした♡' },
  { speaker: '茶羅井', bgKey: '119', text: 'よし次は詩保！お前だ' },
  { speaker: '詩保', bgKey: '119', text: 'はい茶羅井様♡' },
  { speaker: '', text: '— HA24 终 —', end: true },
];

export const HA25_LINES: AvdLineJSON[] = [
  { speaker: '', text: '有理紗と入れ替わる形で詩保が横になる。' },
  { speaker: '詩保', bgKey: '120', text: 'どうぞ私の初めてももらってください' },
  { speaker: '茶羅井', bgKey: '120', text: '詩保も処女なのか？' },
  { speaker: '詩保', bgKey: '120', text: 'はい、シスターでもありましたし、' },
  { speaker: '詩保', bgKey: '120', text: 'それに男の人と接する機会がほとんどなかったので' },
  { speaker: '詩保', bgKey: '121', text: 'ですが今は茶羅井様に処女を捧げられるので' },
  { speaker: '詩保', bgKey: '121', text: 'これで良かったと思っています' },
  { speaker: '詩保', bgKey: '121', text: 'これからはシスターを辞めて' },
  { speaker: '詩保', bgKey: '121', text: '茶羅井様に忠実な下僕となることを誓います' },
  { speaker: '茶羅井', bgKey: '121', text: 'そんなに俺のものになりたいのか？' },
  { speaker: '詩保', bgKey: '121', text: 'はい、なりたいです' },
  { speaker: '詩保', bgKey: '121', text: 'もう今までの人生を全て捨ててでも' },
  { speaker: '詩保', bgKey: '121', text: '茶羅井様のものになりたくて仕方がないのです' },
  { speaker: '茶羅井', bgKey: '121', text: 'そうか、そんなに俺のことが好きか' },
  { speaker: '茶羅井', bgKey: '121', text: 'それなら仕方ないな' },
  { speaker: '茶羅井', bgKey: '121', text: '処女はいただかせてもらうぜ' },
  { speaker: '詩保', bgKey: '121', text: 'はい、お願いします' },
  { speaker: '', bgKey: '122', text: '挿入する茶羅井。' },
  { speaker: '詩保', bgKey: '122', text: 'ああっ、これが初めての痛み…' },
  { speaker: '詩保', bgKey: '123', text: '思ったより痛くないのですね' },
  { speaker: '茶羅井', bgKey: '123', text: '俺のことが好きすぎて痛みとか感じないんじゃないか？' },
  { speaker: '詩保', bgKey: '123', text: 'そうかもしれません' },
  { speaker: '', bgKey: '123', text: '魅了により痛みより幸福が勝っている詩保。' },
  { speaker: '茶羅井', bgKey: '123', text: 'じゃあ動くぞ' },
  { speaker: '', bgKey: '124', text: '茶羅井が腰を動かし始める。' },
  { speaker: '詩保', bgKey: '124', text: 'ああ、すごいです！こんなに気持ちが良いものなのですね！！' },
  { speaker: '詩保', bgKey: '124', text: '(これがセックス……' },
  { speaker: '詩保', bgKey: '124', text: ' こんなに幸せな気持ちになれるものだったなんて･･･)' },
  { speaker: '茶羅井', bgKey: '124', text: 'どうだ？俺の女になった気分は？' },
  { speaker: '詩保', bgKey: '124', text: 'はい、幸せです' },
  { speaker: '詩保', bgKey: '124', text: '幸せすぎておかしくなっちゃいそうです' },
  { speaker: '茶羅井', bgKey: '124', text: 'じゃあもっと幸せな気持ちにしてやるよ！' },
  { speaker: '', bgKey: '125', text: '茶羅井の動きが激しくなる。' },
  { speaker: '詩保', bgKey: '125', text: 'ああっ、すごいです！こんなの気持ち良すぎます！！' },
  { speaker: '詩保', bgKey: '125', text: '(ああ……もうダメ……おかしくなってしまいます)' },
  { speaker: '茶羅井', bgKey: '125', text: '出すぞ！' },
  { speaker: '詩保', bgKey: '125', text: 'はい、出してください！！' },
  { speaker: '', bgKey: '126', text: 'ドピュッビュルルルー' },
  { speaker: '詩保', bgKey: '127', text: 'ああ、熱い……' },
  { speaker: '詩保', bgKey: '127', text: '(これが中に出された感覚……とても心地よいものですね…)' },
  { speaker: '詩保', bgKey: '127', text: '(こんなの知ってしまったら、' },
  { speaker: '詩保', bgKey: '127', text: ' もう他のことなんてどうでも良くなってしまいます…)' },
  { speaker: '', bgKey: '127', text: 'こうして有理紗に続き詩保も茶羅井のものとなるのだった･･･' },
  { speaker: '', text: '— HA25 终 —', end: true },
];

export const HA26_LINES: AvdLineJSON[] = [
  { speaker: '', text: '茶羅井はセイレアの力を行使し' },
  { speaker: '', text: '世界を自分の都合の良い世界に変えた。' },
  { speaker: '', text: 'もう茶羅井に逆らえるものなど存在しない。' },
  { speaker: '有理紗', bgKey: '128', text: '茶羅井様♡' },
  { speaker: '有理紗', bgKey: '128', text: '(茶羅井様のおチンポ…)' },
  { speaker: 'セイレア', bgKey: '128', text: '茶羅井様♡' },
  { speaker: '詩保', bgKey: '128', text: '茶羅井様♡' },
  { speaker: 'ガウ', bgKey: '128', text: 'ご主人様♡' },
  { speaker: '', bgKey: '128', text: '４人の女性が茶羅井にくっ付いている。' },
  { speaker: 'セイレア', bgKey: '128', text: '茶羅井様、どうですかこの世界は' },
  { speaker: '茶羅井', bgKey: '128', text: 'ああ、最高だよ' },
  { speaker: '茶羅井', bgKey: '128', text: 'なんでも俺の思うがまま' },
  { speaker: '茶羅井', bgKey: '128', text: 'こんな素晴らしい世界良いに決まってるだろ！' },
  { speaker: 'セイレア', bgKey: '129', text: 'ありがとうございます♡' },
  { speaker: '詩保', bgKey: '129', text: '私も茶羅井様に何かしたいです' },
  { speaker: '茶羅井', bgKey: '129', text: 'いいんだよ詩保は' },
  { speaker: '茶羅井', bgKey: '129', text: 'そこにいてくれるだけで目の保養になる' },
  { speaker: '詩保', bgKey: '130', text: '茶羅井様ぁ♡んっ' },
  { speaker: '', bgKey: '130', text: 'そう言いながらキスをする詩保。' },
  { speaker: '茶羅井', bgKey: '131', text: 'まったく詩保はいきなりなんだから' },
  { speaker: 'ガウ', bgKey: '132', text: 'ご主人様！ご主人様！ガウは？' },
  { speaker: '茶羅井', bgKey: '132', text: 'ガウ？ああ、良いペットだよ' },
  { speaker: '茶羅井', bgKey: '132', text: 'これからも俺を楽しませてくれ' },
  { speaker: 'ガウ', bgKey: '133', text: 'うん！' },
  { speaker: 'ガウ', bgKey: '133', text: 'ガウ、ご主人様の言うことなんでも聞く！' },
  { speaker: '茶羅井', bgKey: '134', text: '有理紗も良い感じだぞ' },
  { speaker: '有理紗', bgKey: '134', text: 'ありがとうございます' },
  { speaker: '茶羅井', bgKey: '134', text: 'ああ出すぞ･･･ちゃんと飲むんだぞ！' },
  { speaker: '有理紗', bgKey: '134', text: 'ふぁい･･･' },
  { speaker: '', bgKey: '135', text: 'ドピュッビュルルルー' },
  { speaker: '有理紗', bgKey: '136', text: 'んぐんぐ……ぷはっ' },
  { speaker: '有理紗', bgKey: '136', text: '(茶羅井様の精液おいしい…やっぱりこれが一番…)' },
  { speaker: '茶羅井', bgKey: '136', text: '(最高だ･･･)' },
  { speaker: '', bgKey: '136', text: 'もう茶羅井にできないことなどない。' },
  { speaker: '', bgKey: '136', text: '永遠の命と永遠のハーレム' },
  { speaker: '', bgKey: '136', text: 'この世界は茶羅井が飽きるまで続くことになる…' },
  { speaker: '', bgKey: '136', text: '茶羅井エンド' },
  { speaker: '', text: '— HA26 终 —', end: true },
];

export const HB21_LINES: AvdLineJSON[] = [
  { speaker: '有理紗', bgKey: '137', text: '私を捕まえてどうする気？！' },
  { speaker: '', bgKey: '137', text: 'よくわからない椅子に拘束されている有理紗。' },
  { speaker: '小茂田', bgKey: '137', text: 'うーんどうしようかなあ…' },
  { speaker: '小茂田', bgKey: '137', text: '他の反乱分子と同じように' },
  { speaker: '小茂田', bgKey: '137', text: 'このまま感情のない忠実なマシナ兵に洗脳してあげてもいいけど…' },
  { speaker: '小茂田', bgKey: '137', text: '有理紗ちゃん可愛いし特別に僕の女にしてあげるよ' },
  { speaker: '有理紗', bgKey: '137', text: '洗脳…？冗談でしょ！' },
  { speaker: '有理紗', bgKey: '137', text: 'あなたのものになんか絶対にならないんだから！' },
  { speaker: '小茂田', bgKey: '137', text: 'まあ今の有理紗ちゃんじゃ受け入れてくれないよね' },
  { speaker: '小茂田', bgKey: '137', text: 'だから受け入れてくれるようにしっかり洗脳してあげるからね' },
  { speaker: '有理紗', bgKey: '148', text: 'なっ…これってまさか…！？' },
  { speaker: '小茂田', bgKey: '148', text: 'じゃあ始めるよー' },
  { speaker: '有理紗', bgKey: '149', text: 'あがががが、頭が痛いいいいいい' },
  { speaker: '', bgKey: '149', text: '有理紗の頭に装着されている機械から電流が流れ出す。' },
  { speaker: '小茂田', bgKey: '149', text: '最初は痛いかもしれないけど我慢してね' },
  { speaker: '小茂田', bgKey: '149', text: 'まずは洗脳を受け入れやすくするために' },
  { speaker: '小茂田', bgKey: '149', text: '刺激を与えて準備しないとだからね' },
  { speaker: '有理紗', bgKey: '150', text: '止めてーーーーー、今すぐこれを止めてええええええ' },
  { speaker: '小茂田', bgKey: '150', text: 'だーめ' },
  { speaker: '小茂田', bgKey: '150', text: '今のうちにⅠ型の再セットアップをしてこようかな' },
  { speaker: '有理紗', bgKey: '150', text: '待ってーーーー止めてええええええ' },
  { speaker: '', bgKey: '150', text: '小茂田はミディを再セットアップするために部屋を後にする。' },
  { speaker: '', bgKey: '150', text: 'その間有理紗は一人で洗脳装置の電撃を受けていた。' },
  { speaker: '', bgKey: '150', text: 'それから少しして小茂田は戻って来る。' },
  { speaker: '有理紗', bgKey: '151', text: 'あひぃ…あひぃ…' },
  { speaker: '小茂田', bgKey: '151', text: 'ちょっと長くやりすぎたかな、気分はどうだい？' },
  { speaker: '有理紗', bgKey: '151', text: 'お願い…止めて…' },
  { speaker: '小茂田', bgKey: '151', text: '止めて欲しいならほら…' },
  { speaker: '', bgKey: '151', text: '小茂田様に忠誠を誓うこと' },
  { speaker: '有理紗', bgKey: '152', text: 'えっ？' },
  { speaker: '', bgKey: '152', text: '脳内に言葉が浮かんでくる。' },
  { speaker: '有理紗', bgKey: '153', text: 'だめ…そんなこと…' },
  { speaker: '有理紗', bgKey: '154', text: 'ああああああああ' },
  { speaker: '小茂田', bgKey: '154', text: 'ほら、止めて欲しいんでしょ？' },
  { speaker: '有理紗', bgKey: '154', text: '(止めてもらうために演技で言えば…演技…演技だったら…)' },
  { speaker: '有理紗', bgKey: '155', text: '小茂田様に忠誠を誓います…' },
  { speaker: '有理紗', bgKey: '138', text: 'ああああああああなんでえええええええ' },
  { speaker: '小茂田', bgKey: '138', text: '心がこもってないね' },
  { speaker: '小茂田', bgKey: '138', text: '演技って丸わかりだよ' },
  { speaker: '有理紗', bgKey: '138', text: 'ああああああ小茂田様ーーーー小茂田様ああああああ' },
  { speaker: '有理紗', bgKey: '138', text: '(もう何も考えずとにかく言うしか…ここをしのぐためにも…)' },
  { speaker: '有理紗', bgKey: '138', text: '誓いますうううう、小茂田様に忠誠を誓いますうううううう' },
  { speaker: '有理紗', bgKey: '138', text: 'あああああどうしてえええええ' },
  { speaker: '有理紗', bgKey: '138', text: '小茂田様に忠誠を誓いますから！だから止めてくださいいいいい' },
  { speaker: '有理紗', bgKey: '138', text: '(これ以上どうすれば良いっていうの？)' },
  { speaker: '', bgKey: '138', text: '心から忠誠を誓えばいい' },
  { speaker: '有理紗', bgKey: '138', text: '(心からなんて…そんな……)' },
  { speaker: '有理紗', bgKey: '139', text: '(そんな簡単なことに気付けないなんて！！)' },
  { speaker: '有理紗', bgKey: '139', text: '(どうして演技なんてしてたんだろう･･･' },
  { speaker: '有理紗', bgKey: '139', text: ' 心から小茂田様に忠誠を誓えばこれを止めてもらえるのに)' },
  { speaker: '有理紗', bgKey: '140', text: '誓いますうううう！！小茂田様に心から忠誠を誓いますううう！！' },
  { speaker: '小茂田', bgKey: '140', text: 'へえ、心から…それって僕のどんな命令も従ってくれるの？' },
  { speaker: '有理紗', bgKey: '140', text: 'もちろんですうううう！どんな命令でも従いますううう！' },
  { speaker: '有理紗', bgKey: '141', text: '(気持ち良い･･･' },
  { speaker: '有理紗', bgKey: '141', text: ' 小茂田様に忠誠を誓うとどうしてこんなに気持ち良いの･･･)' },
  { speaker: '小茂田', bgKey: '141', text: 'それは本心かな？' },
  { speaker: '有理紗', bgKey: '141', text: 'はい、本心です！！' },
  { speaker: '有理紗', bgKey: '141', text: '身も心も小茂田様のものですうううう！！！' },
  { speaker: '有理紗', bgKey: '141', text: '(ああ･･･気持ち良い！)' },
  { speaker: '有理紗', bgKey: '141', text: '(小茂田様に忠誠を誓うの気持ち良すぎるううう)' },
  { speaker: '', bgKey: '141', text: '洗脳装置から小茂田に忠誠を誓うたびに' },
  { speaker: '', bgKey: '141', text: '快楽信号が送られてきていた。' },
  { speaker: '', bgKey: '141', text: '有理紗はその快楽に完全に呑まれていた。' },
  { speaker: '有理紗', bgKey: '141', text: '小茂田様素敵です！！' },
  { speaker: '有理紗', bgKey: '141', text: '小茂田様最高！！' },
  { speaker: '有理紗', bgKey: '141', text: '(気持ち良い！気持ち良い！気持ち良いいいい！)' },
  { speaker: '有理紗', bgKey: '141', text: '(小茂田様に忠誠誓うだけでこんなに気持ち良いなんて' },
  { speaker: '有理紗', bgKey: '141', text: ' こんなの一生忠誠誓うしかないじゃない！！)' },
  { speaker: '有理紗', bgKey: '141', text: '有理紗は小茂田様のものです！' },
  { speaker: '有理紗', bgKey: '141', text: '有理紗は小茂田様に永遠の忠誠を誓います！' },
  { speaker: '有理紗', bgKey: '141', text: '(ああこれぇ･･･小茂田様ぁ･･････)' },
  { speaker: '有理紗', bgKey: '141', text: '小茂田様ぁ有理紗になんでも命令してくださいいいいい！！' },
  { speaker: '小茂田', bgKey: '141', text: 'その言葉に嘘はない？' },
  { speaker: '有理紗', bgKey: '141', text: 'はいいいいい！心からの言葉ですうううう' },
  { speaker: '小茂田', bgKey: '141', text: 'ふむ･･･洗脳は完了したようだね' },
  { speaker: '小茂田', bgKey: '141', text: 'じゃあトドメに最高の快楽を与えてあげるよ' },
  { speaker: '有理紗', bgKey: '142', text: 'おひょおおおおおおおあああああああ' },
  { speaker: '', bgKey: '142', text: '小茂田様に洗脳されたことを感謝せよ' },
  { speaker: '有理紗', bgKey: '142', text: 'はいぃいいいい感謝しますうううう' },
  { speaker: '有理紗', bgKey: '142', text: '有理紗を洗脳してくれてありがとうございますうううう' },
  { speaker: '有理紗', bgKey: '142', text: '有理紗は小茂田様に心から感謝しますうううううう' },
  { speaker: '', bgKey: '143', text: '絶頂する有理紗。' },
  { speaker: '有理紗', bgKey: '144', text: 'はあ…はあ…小茂田様…小茂田様ぁ…' },
  { speaker: '小茂田', bgKey: '144', text: 'これで完全に心に刻み込めたかな' },
  { speaker: '', bgKey: '145', text: '装置が停止する。' },
  { speaker: '', bgKey: '146', text: '装置が外される。' },
  { speaker: '有理紗', bgKey: '147', text: '小茂田様…今すっごく幸せな気分です' },
  { speaker: '有理紗', bgKey: '147', text: '洗脳していただきありがとうございます' },
  { speaker: '小茂田', bgKey: '147', text: 'そうか、それは良かったよ' },
  { speaker: '', bgKey: '147', text: '有理紗の目に光が戻る。' },
  { speaker: '', bgKey: '147', text: 'だが洗脳された認識はそのままである。' },
  { speaker: '小茂田', bgKey: '147', text: 'じゃあさっそくエッチでもしてもらおうかな' },
  { speaker: '有理紗', bgKey: '147', text: 'はいっ！小茂田様♡' },
  { speaker: '', text: '— HB21 终 —', end: true },
];

export const HB22_LINES: AvdLineJSON[] = [
  { speaker: '小茂田', bgKey: '156', text: 'ほらおいで' },
  { speaker: '', bgKey: '156', text: '椅子に腰かけ勃起したペニスを見せて来る小茂田。' },
  { speaker: '有理紗', bgKey: '156', text: 'では入れますね' },
  { speaker: '', bgKey: '157', text: 'そう言い、小茂田に抱きつく形で挿入する。' },
  { speaker: '有理紗', bgKey: '157', text: 'ああ…これが小茂田様の…' },
  { speaker: '小茂田', bgKey: '157', text: 'どうだい？チンポ入れらた気分は？' },
  { speaker: '有理紗', bgKey: '157', text: '小茂田様を感じることができてとても幸せです' },
  { speaker: '小茂田', bgKey: '157', text: 'それは良かったよ、じゃあ動こうか' },
  { speaker: '', bgKey: '158', text: 'パンパンパンパン' },
  { speaker: '有理紗', bgKey: '158', text: 'あん……ああん……' },
  { speaker: '小茂田', bgKey: '158', text: '僕の女になれてどんな気分だい？' },
  { speaker: '有理紗', bgKey: '159', text: 'はい、とても幸せですうう♡' },
  { speaker: '小茂田', bgKey: '159', text: 'これからも僕の女でいてくれるかい？' },
  { speaker: '有理紗', bgKey: '159', text: 'もちろんですぅ♡' },
  { speaker: '有理紗', bgKey: '159', text: '有理紗は永遠に小茂田様のものですぅ♡' },
  { speaker: '有理紗', bgKey: '159', text: 'あひぃ……いいっ！もっと、もっと激しくしてください' },
  { speaker: '小茂田', bgKey: '159', text: 'わかったよ' },
  { speaker: '小茂田', bgKey: '159', text: 'ほらこれでどうだい' },
  { speaker: '', bgKey: '160', text: '動きが激しくなる。' },
  { speaker: '有理紗', bgKey: '160', text: 'ああんっ気持ち良いです、小茂田様ぁ、愛してますぅ' },
  { speaker: '小茂田', bgKey: '160', text: '僕も有理紗のこと愛してるよ' },
  { speaker: '有理紗', bgKey: '160', text: '嬉しいです小茂田様！' },
  { speaker: '有理紗', bgKey: '160', text: '小茂田様小茂田様ぁ！私もう…イっちゃいそうです…' },
  { speaker: '小茂田', bgKey: '160', text: '僕もそろそろ出そうだよ･･･' },
  { speaker: '小茂田', bgKey: '160', text: 'ああっ出るっ' },
  { speaker: '', bgKey: '161', text: 'ドピュドピュッ' },
  { speaker: '有理紗', bgKey: '162', text: 'ああぁ、小茂田様の精液が私の中に…' },
  { speaker: '小茂田', bgKey: '162', text: 'ふう……よかったよ有理紗ちゃん……' },
  { speaker: '有理紗', bgKey: '162', text: 'ありがとうございます小茂田様♡' },
  { speaker: '小茂田', bgKey: '162', text: 'これからも僕の女として、' },
  { speaker: '小茂田', bgKey: '162', text: 'そしてマシナの兵士として戦ってもらうよ' },
  { speaker: '有理紗', bgKey: '162', text: 'はい、小茂田様に全て従います' },
  { speaker: '有理紗', bgKey: '162', text: 'これからも私のことを使ってください' },
  { speaker: '', bgKey: '162', text: 'こうして有理紗は小茂田の女に堕とされてしまうのだった…' },
  { speaker: '', bgKey: '162', text: '小茂田敗北エンド' },
  { speaker: '', text: '— HB22 终 —', end: true },
];

export const HB23_LINES: AvdLineJSON[] = [
  { speaker: '教皇マルクス', bgKey: '163', text: 'そうやってお尻を突き出すだけでパンツが見えますね' },
  { speaker: '教皇マルクス', bgKey: '163', text: 'やはり丈の短い服にして正解でしたね' },
  { speaker: '詩保', bgKey: '163', text: '教皇様が喜んでくれるのでしたら短くして良かったです' },
  { speaker: '詩保', bgKey: '164', text: 'さあ教皇様' },
  { speaker: '詩保', bgKey: '164', text: '早く私の中に入れてください' },
  { speaker: '', bgKey: '164', text: '期待で愛液が溢れてくる詩保。' },
  { speaker: '教皇マルクス', bgKey: '164', text: 'では入れますね' },
  { speaker: '詩保', bgKey: '164', text: 'はい、来てください教皇様' },
  { speaker: '', bgKey: '165', text: 'ズブリと教皇のペニスが詩保の中に挿入される。' },
  { speaker: '詩保', bgKey: '165', text: 'ああん、教皇様のが入ってくる……' },
  { speaker: '教皇マルクス', bgKey: '165', text: '毎日のようにやっているのにあなたの中はまだまだキツイですね' },
  { speaker: '教皇マルクス', bgKey: '165', text: 'よほど私のペニスを離したくないようですね' },
  { speaker: '詩保', bgKey: '165', text: 'はい、ずっとこうしていたいぐらいです' },
  { speaker: '', bgKey: '166', text: '動き出す教皇。' },
  { speaker: '詩保', bgKey: '166', text: 'ああんっ教皇様気持ち良いですぅ' },
  { speaker: '教皇マルクス', bgKey: '166', text: '私も気持ちいですよ' },
  { speaker: '詩保', bgKey: '166', text: '嬉しいです教皇様' },
  { speaker: '詩保', bgKey: '166', text: 'もっと激しく突いてください' },
  { speaker: '教皇マルクス', bgKey: '166', text: 'いいでしょう' },
  { speaker: '', bgKey: '167', text: 'パンパンと腰を打ち付ける音が響く。' },
  { speaker: '詩保', bgKey: '167', text: 'ああんっ！これ好きですぅ！' },
  { speaker: '', bgKey: '167', text: '詩保は快楽に溺れていた。' },
  { speaker: '教皇マルクス', bgKey: '167', text: 'そろそろ出そうです' },
  { speaker: '詩保', bgKey: '167', text: 'はい教皇様、私の{膣内|なか}にたくさん出してください' },
  { speaker: '教皇マルクス', bgKey: '167', text: 'ああ出ますっ！' },
  { speaker: '', bgKey: '168', text: '教皇は詩保の中に射精した。同時に詩保も絶頂する。' },
  { speaker: '詩保', bgKey: '169', text: 'ああ……熱い……' },
  { speaker: '教皇マルクス', bgKey: '169', text: 'ふう、どうでしたか？' },
  { speaker: '詩保', bgKey: '169', text: 'はいぃ、とても気持ち良かったです…' },
  { speaker: '教皇マルクス', bgKey: '169', text: 'まだまだ相手をしてもらいますよ' },
  { speaker: '詩保', bgKey: '169', text: 'はい、もっと私で気持ち良くなってください' },
  { speaker: '', bgKey: '169', text: 'こうして教皇と何度も交わる詩保だった…' },
  { speaker: '', text: '— HB23 终 —', end: true },
];

export const HB24_LINES: AvdLineJSON[] = [
  { speaker: '有理紗', bgKey: '170', text: '私も詩保みたいに洗脳するの？' },
  { speaker: '', bgKey: '170', text: '詩保に敗北した後、拘束された有理紗。' },
  { speaker: '教皇マルクス', bgKey: '170', text: 'ええ、ですがそれは今ではありません' },
  { speaker: '教皇マルクス', bgKey: '170', text: 'あなたにはまだ抵抗してもらわないといけない理由がありますから' },
  { speaker: '教皇マルクス', bgKey: '170', text: 'ですが、そんな抵抗できない姿を見せられると興奮してきますね' },
  { speaker: '教皇マルクス', bgKey: '170', text: '少し私の性処理に付き合ってもらいましょう' },
  { speaker: '', bgKey: '174', text: 'そう言い勃起したペニスを見せ付けて来る教皇。' },
  { speaker: '有理紗', bgKey: '174', text: '嫌、来ないで！' },
  { speaker: '教皇マルクス', bgKey: '174', text: '嫌がる女性とするのは初めてですね' },
  { speaker: '教皇マルクス', bgKey: '174', text: '皆さん喜んで私に身体を差し出してくれますから' },
  { speaker: '有理紗', bgKey: '174', text: 'それはあなたが洗脳してるからでしょ！' },
  { speaker: '教皇マルクス', bgKey: '174', text: 'ええその通りです' },
  { speaker: '教皇マルクス', bgKey: '174', text: 'ですから新鮮な気持ちですよ' },
  { speaker: '教皇マルクス', bgKey: '174', text: 'さあ、入れますよ！' },
  { speaker: '', bgKey: '175', text: '教皇のペニスが有理紗の中に挿入される。' },
  { speaker: '有理紗', bgKey: '176', text: '痛い！痛いいいい' },
  { speaker: '', bgKey: '176', text: '初めての痛みもあり叫ぶ有理紗。' },
  { speaker: '教皇マルクス', bgKey: '176', text: '初めてだったのですか' },
  { speaker: '教皇マルクス', bgKey: '176', text: 'まあ私には関係ありませんが' },
  { speaker: '', bgKey: '177', text: 'そう言い腰を動かし出す教皇。' },
  { speaker: '有理紗', bgKey: '177', text: 'ううっ' },
  { speaker: '', bgKey: '177', text: '痛みに耐える有理紗。' },
  { speaker: '教皇マルクス', bgKey: '177', text: 'ああ、とても気持ち良いですよ' },
  { speaker: '', bgKey: '177', text: '有理紗のことなど気にせず自分だけ気持ち良くなる教皇。' },
  { speaker: '', bgKey: '177', text: 'パンパンと腰を打ち付ける音が響く。' },
  { speaker: '有理紗', bgKey: '177', text: '痛い…もうやめて…' },
  { speaker: '教皇マルクス', bgKey: '177', text: 'やめるわけないでしょう' },
  { speaker: '教皇マルクス', bgKey: '177', text: 'もっと激しく動きますよ' },
  { speaker: '有理紗', bgKey: '178', text: 'いやああっ！！' },
  { speaker: '', bgKey: '178', text: 'さらに早くなる腰の動き。' },
  { speaker: '教皇マルクス', bgKey: '178', text: 'ああ、出そうですよ！' },
  { speaker: '有理紗', bgKey: '178', text: 'いやいやいやあああああ' },
  { speaker: '', bgKey: '179', text: 'ドピュッ！ビュルルルー！！ドクンドクン……' },
  { speaker: '', bgKey: '180', text: '中に出される精液の感触を感じる有理紗。' },
  { speaker: '有理紗', bgKey: '180', text: 'もう嫌…' },
  { speaker: '詩保', bgKey: '180', text: '教皇様、準備が整いました' },
  { speaker: '教皇マルクス', bgKey: '180', text: 'おっそうですか' },
  { speaker: '教皇マルクス', bgKey: '181', text: '良かったですね有理紗さん' },
  { speaker: '教皇マルクス', bgKey: '181', text: 'これであたなも私の信徒になれますよ' },
  { speaker: '', bgKey: '182', text: '有理紗に手をかざす教皇。' },
  { speaker: '', bgKey: '171', text: 'そう言いながら洗脳魔法を発動する教皇。' },
  { speaker: '有理紗', bgKey: '171', text: '(ああ･･･だめぇ･･･頭が･･･ボーっとしてきて･･･)' },
  { speaker: '有理紗', bgKey: '172', text: '(でもこれで私も･･･詩保と同じ･･･教皇様のものに･･･)' },
  { speaker: '有理紗', bgKey: '172', text: '(教皇様のものに･･･幸せ･･････)' },
  { speaker: '', bgKey: '172', text: '無理やり犯され心が弱っている有理紗は' },
  { speaker: '', bgKey: '172', text: '抵抗する力もなくあっけなく教皇の洗脳魔法に堕ちる…' },
  { speaker: '教皇マルクス', bgKey: '173', text: 'さて･･･次はあの方ですね･･･' },
  { speaker: '教皇マルクス', bgKey: '173', text: '有理紗さんも来るのですよ' },
  { speaker: '有理紗', bgKey: '173', text: 'はい、教皇様' },
  { speaker: '', text: '— HB24 终 —', end: true },
];

export const T21_LINES: AvdLineJSON[] = [
  { speaker: '', text: '教祖の部屋へと連れていかれるセイレア。' },
  { speaker: '', text: 'そのままベッドへ押し倒される。' },
  { speaker: 'セイレア', bgKey: '183', text: 'マルクス様…私…私は…' },
  { speaker: '教皇マルクス', bgKey: '183', text: 'セイレア様、まだ私のことを信じられないのですか？' },
  { speaker: 'セイレア', bgKey: '183', text: '違います…マルクス様こそ支配者にふさわしいと思っています…' },
  { speaker: 'セイレア', bgKey: '183', text: 'ですが女神の力を渡してしまうと、' },
  { speaker: 'セイレア', bgKey: '183', text: '私がこの世界を見守ることができなくなってしまいます…' },
  { speaker: '教皇マルクス', bgKey: '183', text: 'そんなの私の側で一緒に見守ればよいでしょう' },
  { speaker: 'セイレア', bgKey: '183', text: 'ですが…' },
  { speaker: 'セイレア', bgKey: '184', text: 'ああっ、マルクス様何を！？' },
  { speaker: '教皇マルクス', bgKey: '184', text: '口で言ってもわからないようですので、これでわからせてあげます' },
  { speaker: '教皇マルクス', bgKey: '184', text: 'あなたはもう私のものなのです！' },
  { speaker: '教皇マルクス', bgKey: '184', text: 'あなたの力も身体も全て私の物！' },
  { speaker: '教皇マルクス', bgKey: '184', text: 'あなたはただ私に従っていればいいのです！！' },
  { speaker: '', bgKey: '185', text: 'パンパンと激しく音を立てて腰を振る教皇。' },
  { speaker: 'セイレア', bgKey: '185', text: 'マルクス様、やめてください、私おかしくなってしまいます' },
  { speaker: '教皇マルクス', bgKey: '185', text: 'もっとおかしくなりなさい！' },
  { speaker: '教皇マルクス', bgKey: '185', text: '何も考えなくていい！' },
  { speaker: '教皇マルクス', bgKey: '185', text: 'ただ私の命令にだけ従っていればいいのです！' },
  { speaker: 'セイレア', bgKey: '186', text: '(ダメです･･･これ以上は･･･)' },
  { speaker: '', bgKey: '186', text: '洗脳に抗おうとするセイレアだが、' },
  { speaker: '', bgKey: '186', text: '快楽により思考はどんどん侵食されている。' },
  { speaker: 'セイレア', bgKey: '186', text: '(私には世界を見守る使命が･･･)' },
  { speaker: 'セイレア', bgKey: '186', text: '(でもそれって、私がやらなくても･･･)' },
  { speaker: 'セイレア', bgKey: '186', text: '(私はただ見守るしかできなかった･･･' },
  { speaker: 'セイレア', bgKey: '186', text: ' だから世界は戦争なんて始めてしまった･･･)' },
  { speaker: 'セイレア', bgKey: '186', text: '(だったらマルクス様に世界を支配してもらった方が' },
  { speaker: 'セイレア', bgKey: '186', text: ' 平和になるに違いない･･･)' },
  { speaker: 'セイレア', bgKey: '187', text: '(どうして私はこんな簡単なことに気付かなかったのだろう･･･)' },
  { speaker: 'セイレア', bgKey: '187', text: '(マルクス様に力を譲り、世界を支配してもらうことこそ' },
  { speaker: 'セイレア', bgKey: '187', text: ' 世界を平和にする一番の方法だったと言うのに･･･)' },
  { speaker: '教皇マルクス', bgKey: '187', text: 'ほらっ、どうですか？私に力を譲る気になりましたか？' },
  { speaker: 'セイレア', bgKey: '188', text: 'はいっ、譲ります！！' },
  { speaker: 'セイレア', bgKey: '188', text: '私の力全部マルクス様に譲りますううう' },
  { speaker: '教皇マルクス', bgKey: '188', text: 'おお、わかってくれましたか' },
  { speaker: 'セイレア', bgKey: '188', text: 'はい、私はマルクス様に従うだけの存在になりますううう' },
  { speaker: '教皇マルクス', bgKey: '188', text: 'いい返事です' },
  { speaker: '教皇マルクス', bgKey: '188', text: 'これからは私の命令に全て従ってもらいますよ' },
  { speaker: 'セイレア', bgKey: '188', text: 'はいぃ、どんな命令でも従います！' },
  { speaker: '教皇マルクス', bgKey: '188', text: 'この世界の女神も私のものに･･･' },
  { speaker: '教皇マルクス', bgKey: '188', text: 'これはもう私は世界を支配したと言っても過言ではないですね' },
  { speaker: '', bgKey: '189', text: '女神を堕とした興奮で教皇の腰を振る速度も上がる。' },
  { speaker: 'セイレア', bgKey: '189', text: 'ああんっ、そうです！' },
  { speaker: 'セイレア', bgKey: '189', text: 'マルクス様は世界の支配者です！！' },
  { speaker: 'セイレア', bgKey: '189', text: '私の力を全てお譲りしますので、' },
  { speaker: 'セイレア', bgKey: '189', text: 'どうかこの世界をマルクス様の手で支配してくださいいいい' },
  { speaker: '教皇マルクス', bgKey: '189', text: 'ええ任せてください！ああっ、出そうです･･･' },
  { speaker: '教皇マルクス', bgKey: '189', text: '出るっ！' },
  { speaker: '', bgKey: '190', text: 'ドピュッ！ビュルルルー！！ドクンドクン……。' },
  { speaker: 'セイレア', bgKey: '190', text: 'ああ、マルクス様のが私の中に入ってきます' },
  { speaker: '教皇マルクス', bgKey: '191', text: 'ふう･･･中々良かったですよ' },
  { speaker: 'セイレア', bgKey: '191', text: 'ありがとうございます、マルクス様♡' },
  { speaker: '教皇マルクス', bgKey: '191', text: 'まずは私が世界の支配者であると示すために、' },
  { speaker: '教皇マルクス', bgKey: '191', text: 'あなたにも働いてもらいますよ' },
  { speaker: 'セイレア', bgKey: '191', text: 'はい、何でも申しつけてください' },
  { speaker: '', bgKey: '191', text: 'セイレアが教皇を世界の支配者だと宣言。' },
  { speaker: '', bgKey: '191', text: 'セイレアの力と教皇の洗脳魔法を合わせた大規模な魔法を発動し、' },
  { speaker: '', bgKey: '191', text: 'このことに疑問を持つものは誰一人いなくなった。' },
  { speaker: '', bgKey: '191', text: 'こうして世界はマルクスのものになる。' },
  { speaker: '', bgKey: '191', text: '歪んだ形ではあるが世界は平和になったのだった。' },
  { speaker: '', text: '— T21 终 —', end: true },
];

export const T22_LINES: AvdLineJSON[] = [
  { speaker: 'セイレア', bgKey: '192', text: 'マルクス様♡' },
  { speaker: '詩保', bgKey: '192', text: 'マルクス様♡' },
  { speaker: '有理紗', bgKey: '192', text: 'マルクス様♡' },
  { speaker: '', bgKey: '192', text: '３人の女性に奉仕されているマルクス。' },
  { speaker: '', bgKey: '192', text: '彼は教皇の座を越えた存在になったため' },
  { speaker: '', bgKey: '192', text: '教皇という肩書は捨てていた。' },
  { speaker: '', bgKey: '192', text: '世界中の人に『マルクス様』と呼ばせている。' },
  { speaker: '', bgKey: '192', text: 'それはこの世界の女神であったセイレアも例外ではない。' },
  { speaker: 'セイレア', bgKey: '193', text: 'マルクス様のおかげで、今日も世界は平和です' },
  { speaker: 'マルクス', bgKey: '193', text: 'そうでしょう' },
  { speaker: 'マルクス', bgKey: '193', text: '私に任せて正解だったでしょう？' },
  { speaker: 'セイレア', bgKey: '193', text: 'はい' },
  { speaker: 'セイレア', bgKey: '193', text: 'この平和はマルクス様でなければ成しえなかったでしょう' },
  { speaker: 'セイレア', bgKey: '193', text: '本当に感謝しています' },
  { speaker: 'マルクス', bgKey: '193', text: '良いのですよ' },
  { speaker: 'マルクス', bgKey: '193', text: '私ほどの存在など他にいないでしょうから、' },
  { speaker: 'マルクス', bgKey: '193', text: 'これからも私がこの世界を支してあげますよ' },
  { speaker: 'マルクス', bgKey: '193', text: 'セイレアのおかげで無限の命も手に入りましたしね' },
  { speaker: 'セイレア', bgKey: '193', text: 'はい、これからも永遠にこの世界の支配をお願いします♡' },
  { speaker: 'マルクス', bgKey: '193', text: '詩保も私の勝利に貢献してくれてありがとうございます' },
  { speaker: 'マルクス', bgKey: '193', text: '当然のことをしたまでです' },
  { speaker: 'マルクス', bgKey: '193', text: '有理紗は私に奉仕できることに感謝するのですよ' },
  { speaker: '有理紗', bgKey: '193', text: 'はい、もちろんですぅ' },
  { speaker: '有理紗', bgKey: '193', text: '普通なら会うことすらできない存在であるマルクス様に、' },
  { speaker: '有理紗', bgKey: '193', text: '元勇者と言うだけで優遇してもらって本当に感謝しています' },
  { speaker: '', bgKey: '193', text: '３人とも心を込めてマルクスに奉仕する。' },
  { speaker: 'マルクス', bgKey: '193', text: 'ああ皆さん良いですよ' },
  { speaker: '有理紗＆詩保＆セイレア', bgKey: '193', text: 'マルクス様ぁ' },
  { speaker: 'マルクス', bgKey: '193', text: 'そろそろ出そうですよ' },
  { speaker: '', bgKey: '194', text: 'ドピュッ！ビュルルルー！！' },
  { speaker: '', bgKey: '195', text: '勢いよく射精された精液が３人の顔にかかる。' },
  { speaker: 'セイレア', bgKey: '195', text: 'ああ…マルクス様の精液…' },
  { speaker: '有理紗', bgKey: '195', text: 'あったかい…' },
  { speaker: '詩保', bgKey: '195', text: '幸せですぅ' },
  { speaker: '', bgKey: '195', text: '３人とも教皇の精液を受けてうっとりしている。' },
  { speaker: 'マルクス', bgKey: '195', text: 'また溜まったら奉仕してもらいますからね' },
  { speaker: '有理紗＆詩保＆セイレア', bgKey: '195', text: 'はい、いつでも呼んでくださいマルクス様♡' },
  { speaker: '', bgKey: '195', text: '女神の力で不老不死となったマルクスは' },
  { speaker: '', bgKey: '195', text: '永遠にハーレムを楽しむことになる。' },
  { speaker: '', bgKey: '195', text: '同じく不老不死のセイレアと有理紗と詩保は' },
  { speaker: '', bgKey: '195', text: 'マルクスに末永く愛され続けるのだった…' },
  { speaker: '', bgKey: '195', text: 'マルクスエンド' },
  { speaker: '', text: '— T22 终 —', end: true },
];

export const HC1_LINES: AvdLineJSON[] = [
  { speaker: '有理紗', bgKey: '196', text: 'おクスリ…おクスリください･･･' },
  { speaker: '山賊ボス', bgKey: '196', text: 'すっかり薬の虜になってしまったな' },
  { speaker: 'ガウ', bgKey: '203', text: 'この女、もうダメじゃないですか？' },
  { speaker: 'ガウ', bgKey: '203', text: '捨てちゃったらどうですか？' },
  { speaker: '山賊ボス', bgKey: '203', text: '勇者は死なないんだ' },
  { speaker: '山賊ボス', bgKey: '203', text: '永遠に肉便器にできるんだから捨てるなんてもったいない' },
  { speaker: '山賊ボス', bgKey: '203', text: 'こうして心を壊して永遠に飼ってやるのが正解だろ' },
  { speaker: 'ガウ', bgKey: '204', text: 'そうなんですね！さすがご主人様！' },
  { speaker: '', bgKey: '204', text: 'ガウの態度も依然とは大違いだった。' },
  { speaker: '', bgKey: '204', text: '有理紗を倒した功績もあり、' },
  { speaker: '', bgKey: '204', text: 'ボスはガウにとても優しく接するようになった。' },
  { speaker: '', bgKey: '204', text: '生まれてからずっと奴隷として育てられてきて' },
  { speaker: '', bgKey: '204', text: '愛情というものを知らなかったガウにとって、' },
  { speaker: '', bgKey: '204', text: 'その優しさは十分すぎるものだった。' },
  { speaker: '', bgKey: '204', text: '今のガウは優しく飼ってもらえていることで幸せを感じている。' },
  { speaker: '山賊ボス', bgKey: '204', text: 'おい、薬を持ってきてやれ' },
  { speaker: '山賊', bgKey: '204', text: 'はい' },
  { speaker: '', bgKey: '205', text: '一気に飲み干す有理紗。' },
  { speaker: '有理紗', bgKey: '206', text: 'あああああきたあああああこれえええええ' },
  { speaker: '有理紗', bgKey: '206', text: 'これしゅごいのおおおおお' },
  { speaker: '', bgKey: '207', text: '薬を飲んだだけで絶頂する有理紗。' },
  { speaker: '山賊ボス', bgKey: '208', text: 'じゃあお前たち、こいつのこと頼んだぞ' },
  { speaker: '山賊たち', bgKey: '208', text: 'はい、ボス！' },
  { speaker: '山賊ボス', bgKey: '208', text: 'じゃあガウ、俺たちは二人で愛し合おうな' },
  { speaker: 'ガウ', bgKey: '208', text: 'はいご主人様♡' },
  { speaker: '', bgKey: '208', text: 'そう言いボスとガウは去っていく。' },
  { speaker: '山賊', bgKey: '209', text: 'じゃあ俺のチンポ咥えてくれよ' },
  { speaker: '山賊', bgKey: '209', text: '俺のもしごいてくれよ' },
  { speaker: '', bgKey: '209', text: '山賊たちがペニスを取り出す。' },
  { speaker: '有理紗', bgKey: '209', text: 'あぁ･･･おチンポ･･･早くおチンポちょうだい･･･' },
  { speaker: '', bgKey: '209', text: '薬とペニス漬けの日々は有理紗の心を完全に壊し、' },
  { speaker: '', bgKey: '209', text: '今では薬とペニスのことしか頭になくなっていた。' },
  { speaker: '有理紗', bgKey: '197', text: '(おチンポ･･･おチンポ･･･)' },
  { speaker: '', bgKey: '199', text: '夢中で山賊のペニスをしごく有理紗。' },
  { speaker: '山賊', bgKey: '199', text: 'ああ気持ちいい' },
  { speaker: '山賊', bgKey: '199', text: '俺もだ' },
  { speaker: '有理紗', bgKey: '199', text: '(ああ、おチンポ美味しい…' },
  { speaker: '有理紗', bgKey: '199', text: ' おクスリ飲んでおチンポもらうの最高…)' },
  { speaker: '山賊', bgKey: '199', text: '永遠に使える肉便器とか最高だな' },
  { speaker: '山賊', bgKey: '199', text: 'そうだな、勇者様様だな' },
  { speaker: '有理紗', bgKey: '198', text: '(勇者…？なんだっけそれ？聞いたことがあるような)' },
  { speaker: '山賊', bgKey: '198', text: 'おらっ手が止まってるぞ' },
  { speaker: '有理紗', bgKey: '198', text: '(勇者とかどうでもいいか' },
  { speaker: '有理紗', bgKey: '198', text: ' 私にはおクスリとおチンポがあればそれでいいんだから･･･)' },
  { speaker: '山賊', bgKey: '198', text: 'ああイキそう' },
  { speaker: '山賊', bgKey: '198', text: '俺も出そうだ' },
  { speaker: '有理紗', bgKey: '198', text: '(来る･･･)' },
  { speaker: '有理紗', bgKey: '200', text: '(精液きたぁああああ)' },
  { speaker: '', bgKey: '201', text: '精液を受けただけで絶頂する有理紗。' },
  { speaker: '山賊', bgKey: '201', text: 'ふう、出した出した' },
  { speaker: '山賊', bgKey: '202', text: 'じゃあ次俺な' },
  { speaker: '有理紗', bgKey: '202', text: '(まだおチンポあるの？嬉しい♡)' },
  { speaker: '', bgKey: '202', text: 'こうして有理紗は山賊たちの肉便器になるのだった。' },
  { speaker: '', bgKey: '202', text: '山賊敗北エンド' },
  { speaker: '', text: '— HC1 终 —', end: true },
];

export const HC2_LINES: AvdLineJSON[] = [
  { speaker: '有理紗', bgKey: '210', text: 'おクスリ…おクスリください･･･' },
  { speaker: '詩保', bgKey: '210', text: '私もおクスリください…あれが無いと私もう耐えられないんです…' },
  { speaker: '山賊ボス', bgKey: '210', text: 'すっかり薬の虜になってしまったな' },
  { speaker: 'ガウ', bgKey: '217', text: 'この女たち、もうダメじゃないですか？' },
  { speaker: 'ガウ', bgKey: '217', text: '捨てちゃったらどうですか？' },
  { speaker: '山賊ボス', bgKey: '217', text: '勇者は死なないんだ' },
  { speaker: '山賊ボス', bgKey: '217', text: '永遠に肉便器にできるんだから捨てるなんてもったいない' },
  { speaker: '山賊ボス', bgKey: '217', text: 'こうして心を壊して永遠に飼ってやるのが正解だろ' },
  { speaker: 'ガウ', bgKey: '218', text: 'そうなんですね！さすがご主人様！' },
  { speaker: '', bgKey: '218', text: 'ガウの態度も依然とは大違いだった。' },
  { speaker: '', bgKey: '218', text: '有理紗を倒した功績もあり、' },
  { speaker: '', bgKey: '218', text: 'ボスはガウにとても優しく接するようになった。' },
  { speaker: '', bgKey: '218', text: '生まれてからずっと奴隷として育てられてきて' },
  { speaker: '', bgKey: '218', text: '愛情というものを知らなかったガウにとって、' },
  { speaker: '', bgKey: '218', text: 'その優しさは十分すぎるものだった。' },
  { speaker: '', bgKey: '218', text: '今のガウは優しく飼ってもらえていることで幸せを感じている。' },
  { speaker: '山賊ボス', bgKey: '218', text: 'おい、薬を持ってきてやれ' },
  { speaker: '山賊', bgKey: '218', text: 'はい' },
  { speaker: '', bgKey: '219', text: '一気に飲み干す二人。' },
  { speaker: '有理紗', bgKey: '220', text: 'あああああきたあああああこれえええええ' },
  { speaker: '有理紗', bgKey: '220', text: 'これしゅごいのおおおおお' },
  { speaker: '詩保', bgKey: '220', text: 'あひいいいいい、しゅごいいいいいいい' },
  { speaker: '詩保', bgKey: '220', text: '頭おかしくなりゅううううううう' },
  { speaker: '', bgKey: '221', text: '薬を飲んだだけで絶頂する有理紗と詩保。' },
  { speaker: '山賊ボス', bgKey: '222', text: 'じゃあお前たち、こいつらのこと頼んだぞ' },
  { speaker: '山賊たち', bgKey: '222', text: 'はい、ボス！' },
  { speaker: '山賊ボス', bgKey: '222', text: 'じゃあガウ、俺たちは二人で愛し合おうな' },
  { speaker: 'ガウ', bgKey: '222', text: 'はいご主人様♡' },
  { speaker: '', bgKey: '222', text: 'そう言いボスとガウは去っていく。' },
  { speaker: '山賊', bgKey: '223', text: 'じゃあ俺のチンポ咥えてくれよ' },
  { speaker: '山賊', bgKey: '223', text: '俺のもしごいてくれよ' },
  { speaker: '山賊', bgKey: '223', text: '俺はこっちを使わせてもらおうかな' },
  { speaker: '', bgKey: '223', text: '山賊たちがペニスを取り出す。' },
  { speaker: '有理紗', bgKey: '223', text: 'あぁ･･･おチンポ･･･早くおチンポちょうだい･･･' },
  { speaker: '詩保', bgKey: '223', text: '私もおチンポ欲しいですぅ･･･' },
  { speaker: '', bgKey: '223', text: '薬とペニス漬けの日々は有理紗と詩保の心を完全に壊し、' },
  { speaker: '', bgKey: '223', text: '今では薬とペニスのことしか頭になくなっていた。' },
  { speaker: '有理紗', bgKey: '211', text: '(おチンポ･･･おチンポ･･･)' },
  { speaker: '詩保', bgKey: '211', text: '(ああこれぇ･･･これがないと私おかしくなってしまいますぅ)' },
  { speaker: '', bgKey: '212', text: '夢中で山賊のペニスをしごく有理紗と詩保。' },
  { speaker: '山賊', bgKey: '212', text: 'ああ気持ちいい' },
  { speaker: '山賊', bgKey: '212', text: '俺もだ' },
  { speaker: '有理紗', bgKey: '212', text: '(ああ、おチンポ美味しい…' },
  { speaker: '有理紗', bgKey: '212', text: ' おクスリ飲んでおチンポもらうの最高…)' },
  { speaker: '詩保', bgKey: '212', text: '(おクスリ…おチンポ…おクスリ…おチンポ…)' },
  { speaker: '山賊', bgKey: '212', text: '永遠に使える肉便器とか最高だな' },
  { speaker: '山賊', bgKey: '212', text: 'そうだな、勇者様様だな' },
  { speaker: '有理紗', bgKey: '213', text: '(勇者…？なんだっけそれ？聞いたことがあるような)' },
  { speaker: '山賊', bgKey: '213', text: 'おらっ手が止まってるぞ' },
  { speaker: '有理紗', bgKey: '213', text: '(勇者とかどうでもいいか' },
  { speaker: '有理紗', bgKey: '213', text: ' 私にはおクスリとおチンポがあればそれでいいんだから･･･)' },
  { speaker: '山賊', bgKey: '213', text: 'ああイキそう' },
  { speaker: '山賊', bgKey: '213', text: '俺も出そうだ' },
  { speaker: '山賊', bgKey: '213', text: '俺もイクっ' },
  { speaker: '山賊', bgKey: '213', text: 'ああ出るっ' },
  { speaker: '有理紗', bgKey: '214', text: '(精液きたぁああああ)' },
  { speaker: '詩保', bgKey: '214', text: '(ああきたぁ)' },
  { speaker: '', bgKey: '215', text: '精液を受けただけで絶頂する有理紗と詩保。' },
  { speaker: '山賊', bgKey: '215', text: 'ふう、出した出した' },
  { speaker: '山賊', bgKey: '216', text: 'じゃあ次俺な' },
  { speaker: '有理紗', bgKey: '216', text: '(まだおチンポあるの？嬉しい♡)' },
  { speaker: '詩保', bgKey: '216', text: '(おチンポ…おチンポ…おチンポ…♡)' },
  { speaker: '', bgKey: '216', text: 'こうして有理紗と詩保は山賊たちの肉便器になるのだった。' },
  { speaker: '', bgKey: '216', text: '山賊敗北エンド' },
  { speaker: '', text: '— HC2 终 —', end: true },
];

export const T3_LINES: AvdLineJSON[] = [
  { speaker: '', text: 'こうして狂信者によるセックス指導が始まった。' },
  { speaker: '狂信者', bgKey: '224', text: 'ではまずはセックスに不要な処女は捨てましょうね' },
  { speaker: '有理紗', bgKey: '224', text: 'はいお願いします！' },
  { speaker: '', bgKey: '231', text: 'そう言って挿入する狂信者。' },
  { speaker: '有理紗', bgKey: '231', text: '痛っ…' },
  { speaker: '狂信者', bgKey: '231', text: 'まあこうなりますよね' },
  { speaker: '狂信者', bgKey: '231', text: 'こんなことでは男性を誘惑することはできませんからね' },
  { speaker: '狂信者', bgKey: '231', text: '処女を捨てられて良かったでしょう' },
  { speaker: '有理紗', bgKey: '232', text: 'はい！あなたには感謝しかないです！' },
  { speaker: '有理紗', bgKey: '232', text: '私の処女を捨ててくれてありがとうございます！！' },
  { speaker: '狂信者', bgKey: '232', text: '初めてですし、まずは慣らすためにゆっくりと動きますよ' },
  { speaker: '', bgKey: '233', text: 'そう言いゆっくりとピストンを始める。' },
  { speaker: '有理紗', bgKey: '233', text: 'うう…やっぱり痛いです' },
  { speaker: '狂信者', bgKey: '233', text: '我慢するのです。時期に良くなってきますから' },
  { speaker: '', bgKey: '233', text: 'そう言いしばらくの間はゆっくりとしたピストンが続く。' },
  { speaker: '有理紗', bgKey: '234', text: 'あの、痛くなくなってきたかもしれません' },
  { speaker: '狂信者', bgKey: '234', text: 'それは良かったです' },
  { speaker: '狂信者', bgKey: '234', text: 'ではこれからは男性を喜ばせるセックスの指導をしていきますよ' },
  { speaker: '有理紗', bgKey: '234', text: 'はい、よろしくお願いします' },
  { speaker: '狂信者', bgKey: '235', text: 'では挿入からやり直します' },
  { speaker: '', bgKey: '235', text: 'そう言いペニスを抜く狂信者。' },
  { speaker: '狂信者', bgKey: '235', text: '入れてもらう時も、男性が喜ぶような言動を心がけるのです' },
  { speaker: '有理紗', bgKey: '235', text: 'わかりました' },
  { speaker: '狂信者', bgKey: '235', text: 'ほら' },
  { speaker: '狂信者', bgKey: '235', text: '『私のおマンコにそのたくましいおチンポを入れてください』' },
  { speaker: '狂信者', bgKey: '235', text: 'と言いなさい' },
  { speaker: '有理紗', bgKey: '236', text: 'はい！' },
  { speaker: '有理紗', bgKey: '236', text: '私のおマンコにそのたくましいおチンポを入れてください！' },
  { speaker: '狂信者', bgKey: '236', text: '良いでしょう、入れますよ' },
  { speaker: '', bgKey: '237', text: '再び挿入される有理紗。' },
  { speaker: '有理紗', bgKey: '237', text: 'んんっ' },
  { speaker: '', bgKey: '237', text: 'まだ慣れないのか、抵抗感のある反応をする有理紗。' },
  { speaker: '狂信者', bgKey: '237', text: '違いますよ、そこは嘘でも喘いでください' },
  { speaker: '狂信者', bgKey: '237', text: 'チンポを入れたことで気持ち良くなったと思ってもらわないと' },
  { speaker: '有理紗', bgKey: '237', text: 'すみません' },
  { speaker: '狂信者', bgKey: '237', text: 'では挿入からやり直しますよ' },
  { speaker: '', bgKey: '238', text: 'ペニスが抜かれる。' },
  { speaker: '有理紗', bgKey: '225', text: '私のおマンコにそのたくましいおチンポを入れてください！' },
  { speaker: '', bgKey: '225', text: '再び入れてもらうための言葉を発する有理紗。' },
  { speaker: '有理紗', bgKey: '226', text: 'ああんっ、あなたのたくましいおチンポが入ってきてます' },
  { speaker: '狂信者', bgKey: '226', text: '良いですね、その調子です' },
  { speaker: '狂信者', bgKey: '226', text: 'では動きますよ' },
  { speaker: '有理紗', bgKey: '226', text: 'はい！' },
  { speaker: '', bgKey: '227', text: '腰を動かす狂信者。' },
  { speaker: '有理紗', bgKey: '227', text: 'んんっ、あんっ' },
  { speaker: '狂信者', bgKey: '227', text: 'まだまだ甘いですよ' },
  { speaker: '狂信者', bgKey: '227', text: 'もっと良い反応をするように頑張ってください' },
  { speaker: '有理紗', bgKey: '227', text: 'はい、頑張ります！' },
  { speaker: '', bgKey: '227', text: 'その後もセックス指導は続く。' },
  { speaker: '', bgKey: '228', text: 'ピストンも徐々に早くなっていく。' },
  { speaker: '有理紗', bgKey: '228', text: 'ああんっ、良いっ、あなたのおチンポ気持ち良いです！' },
  { speaker: '有理紗', bgKey: '228', text: 'もっともっと動いてください！' },
  { speaker: '狂信者', bgKey: '228', text: 'かなり良くなりましたね' },
  { speaker: '有理紗', bgKey: '228', text: 'ありがとうございます' },
  { speaker: '狂信者', bgKey: '228', text: 'ああ、そろそろ出そうです' },
  { speaker: '狂信者', bgKey: '228', text: '出してもらう時はどう言うんでしたか？' },
  { speaker: '有理紗', bgKey: '228', text: 'はい、中に…中に出してください！！' },
  { speaker: '狂信者', bgKey: '228', text: '良いですね' },
  { speaker: '狂信者', bgKey: '228', text: 'では出しますよ' },
  { speaker: '有理紗', bgKey: '228', text: 'はいっ！来てください！あなたの精子を私の中に出してください！' },
  { speaker: '狂信者', bgKey: '228', text: 'うっ' },
  { speaker: '', bgKey: '229', text: '中に出される有理紗。' },
  { speaker: '有理紗', bgKey: '230', text: 'ああっ、出てる、熱いのがドクドクと注がれてます……' },
  { speaker: '有理紗', bgKey: '230', text: 'はぁはぁ……' },
  { speaker: '狂信者', bgKey: '230', text: 'いかがでしたか？' },
  { speaker: '有理紗', bgKey: '230', text: 'ご指導ありがとうございます' },
  { speaker: '有理紗', bgKey: '230', text: 'これで誰に抱かれても大丈夫だと思います' },
  { speaker: '狂信者', bgKey: '230', text: 'そうですか' },
  { speaker: '狂信者', bgKey: '230', text: 'ではこれからは共に勧誘活動頑張りましょう' },
  { speaker: '有理紗', bgKey: '230', text: 'はい' },
  { speaker: '', text: '— T3 终 —', end: true },
];

export const HD1_LINES: AvdLineJSON[] = [
  { speaker: '機械音声', bgKey: '239', text: '反乱分子の捕獲に成功' },
  { speaker: '機械音声', bgKey: '239', text: 'これよりブレインウォッシュを開始します' },
  { speaker: '有理紗', bgKey: '239', text: 'ブレインウォッシュ…？' },
  { speaker: '有理紗', bgKey: '239', text: '洗脳ってこと？！マズイ！早く抜け出さないと…' },
  { speaker: '有理紗', bgKey: '239', text: 'ダメ拘束がきつくて抜け出せない…' },
  { speaker: '有理紗', bgKey: '242', text: '何！？これで洗脳する気！？' },
  { speaker: '機械音声', bgKey: '242', text: 'まずは記憶の消去を行います' },
  { speaker: '有理紗', bgKey: '242', text: '記憶の消去…？いやああああ離して！！消さないで！！！' },
  { speaker: '有理紗', bgKey: '243', text: 'あああああああ頭が痛いいいいいい' },
  { speaker: '有理紗', bgKey: '243', text: '脳みそが焼ける焼けてるううううううう' },
  { speaker: '有理紗', bgKey: '243', text: '(ダメ、忘れないようにしないと！' },
  { speaker: '有理紗', bgKey: '243', text: ' 私の記憶消えないように思い出し続けないと！！)' },
  { speaker: '有理紗', bgKey: '244', text: 'ぐぎぎぎぎぎぎぎ' },
  { speaker: '', bgKey: '244', text: '脳が焼けるような痛みに必死に耐えようとする有理紗。' },
  { speaker: '有理紗', bgKey: '244', text: '(思い出さないと…私の名前、私の名前は…)' },
  { speaker: '有理紗', bgKey: '244', text: '(私の名前は･･････)' },
  { speaker: '有理紗', bgKey: '245', text: '(あれ？私の名前…)' },
  { speaker: '有理紗', bgKey: '245', text: '(私…私･･････)' },
  { speaker: '有理紗', bgKey: '245', text: '(私って…誰…？)' },
  { speaker: '機械音声', bgKey: '246', text: '記憶消去完了' },
  { speaker: '機械音声', bgKey: '246', text: '感情の制御に移ります' },
  { speaker: '有理紗', bgKey: '247', text: '(ああ…気持ち良い…頭が真っ白になる…)' },
  { speaker: '', bgKey: '247', text: '先ほどまで脳が焼けるような痛みだったが、' },
  { speaker: '', bgKey: '247', text: '今は脳に走る電撃が心地よく感じている。' },
  { speaker: '', bgKey: '247', text: 'もう有理紗は何の思考も残っていなかった。' },
  { speaker: '', bgKey: '247', text: 'ただボーっとしているような状態である。' },
  { speaker: '機械音声', bgKey: '247', text: '感情消失確認' },
  { speaker: '機械音声', bgKey: '247', text: '最終工程へ移ります' },
  { speaker: '', bgKey: '247', text: '完全に無となっている有理紗の中に１つの文章が浮かび上がる。' },
  { speaker: '', bgKey: '247', text: '『マシナ国に忠誠を』' },
  { speaker: '有理紗', bgKey: '247', text: 'マシナ国に…忠誠を…' },
  { speaker: '', bgKey: '247', text: '無意識に復唱する有理紗。' },
  { speaker: '', bgKey: '247', text: '『マシナ国に忠誠を』' },
  { speaker: '有理紗', bgKey: '247', text: 'マシナ国に忠誠を' },
  { speaker: '', bgKey: '247', text: '『マシナ国に忠誠を』' },
  { speaker: '有理紗', bgKey: '248', text: 'マシナ国に忠誠を！' },
  { speaker: '', bgKey: '248', text: '復唱するたびに有理紗の中にマシナ国の情報が入って来る。' },
  { speaker: '有理紗', bgKey: '248', text: '(私はマシナ国に忠誠を誓う兵士…)' },
  { speaker: '有理紗', bgKey: '248', text: '(私はマシナ国のために戦うだけの存在…)' },
  { speaker: '機械音声', bgKey: '249', text: 'ブレインウォッシュ完了' },
  { speaker: '機械音声', bgKey: '249', text: '拘束を解除します' },
  { speaker: '', bgKey: '240', text: 'まず洗脳装置が外される。' },
  { speaker: '有理紗', bgKey: '241', text: 'マシナ国に忠誠を！' },
  { speaker: '', bgKey: '241', text: '有理紗にはもうマシナ国のことしか頭になかった。' },
  { speaker: '', bgKey: '241', text: 'こうして有理紗は、一般兵として前線へと送られるのだった･･･' },
  { speaker: '', text: '— HD1 终 —', end: true },
];

export const HD2_LINES: AvdLineJSON[] = [
  { speaker: '', text: '一般兵となった有理紗は前線部隊にいた。' },
  { speaker: '全員', bgKey: '250', text: '「「「マシナ国に忠誠を」」」' },
  { speaker: '', bgKey: '250', text: '他の洗脳された女性たちと共にマシナ国への忠誠を叫ぶ有理紗。' },
  { speaker: 'ムノー上官', bgKey: '251', text: 'よし！次に俺に対しての挨拶！！' },
  { speaker: '全員', bgKey: '252', text: '「「「ムノー上官に忠誠を！！」」」' },
  { speaker: 'ムノー上官', bgKey: '252', text: '何度見ても凄い眺めだな…' },
  { speaker: 'ムノー上官', bgKey: '253', text: '前線に送られてきた兵士は俺の命令を何でも聞くから' },
  { speaker: 'ムノー上官', bgKey: '253', text: '好き放題できて最高だな' },
  { speaker: 'ムノー上官', bgKey: '253', text: '小茂田様には感謝しかない' },
  { speaker: 'ムノー上官', bgKey: '253', text: 'さて今日の相手は誰にしようかな･･･' },
  { speaker: '', bgKey: '253', text: 'スカートをたくし上げて静止している女性兵士を' },
  { speaker: '', bgKey: '253', text: '品定めするような目で見る上官。' },
  { speaker: 'ムノー上官', bgKey: '254', text: 'よし！今日はお前だ！' },
  { speaker: '有理紗', bgKey: '255', text: 'はい、承知いたしました！！' },
  { speaker: 'ムノー上官', bgKey: '255', text: '何をされるかわかっているか？' },
  { speaker: '有理紗', bgKey: '255', text: 'はい！ムノー上官の性処理であります！' },
  { speaker: 'ムノー上官', bgKey: '255', text: '嫌じゃないのか？' },
  { speaker: '有理紗', bgKey: '255', text: 'そんなわけありません！' },
  { speaker: '有理紗', bgKey: '255', text: 'マシナ国のため、上官の命令に従うのは当然のこと' },
  { speaker: '有理紗', bgKey: '255', text: 'どんな命令でも喜んで従います！！' },
  { speaker: 'ムノー上官', bgKey: '255', text: 'ははは、本当に最高だな' },
  { speaker: 'ムノー上官', bgKey: '255', text: 'そういやお前、名前は？' },
  { speaker: '有理紗', bgKey: '255', text: '私のような一般兵に名前などありません！' },
  { speaker: '', bgKey: '255', text: '記憶消去をされている有理紗は、' },
  { speaker: '', bgKey: '255', text: '自分の名前を思い出すことすらできない。' },
  { speaker: '', bgKey: '255', text: 'だがそれはマシナ国のために必要のないこと。' },
  { speaker: '', bgKey: '255', text: '有理紗は自分の名前がわからないことを気にも留めていない。' },
  { speaker: 'ムノー上官', bgKey: '255', text: 'そうだったな･･･' },
  { speaker: 'ムノー上官', bgKey: '255', text: '反抗して一般兵にされた者は記憶消去処理をされて' },
  { speaker: 'ムノー上官', bgKey: '255', text: '名前も忘れてるんだったな･･･' },
  { speaker: 'ムノー上官', bgKey: '255', text: 'よし、お前は今日から１７番だ！' },
  { speaker: 'ムノー上官', bgKey: '255', text: '俺の１７番目の女という意味だ！' },
  { speaker: '１７番(有理紗)', bgKey: '255', text: 'わかりました！今日から私は１７番です！！' },
  { speaker: 'ムノー上官', bgKey: '255', text: '良い返事だ！' },
  { speaker: 'ムノー上官', bgKey: '255', text: 'じゃあ後で俺の部屋に来なさい' },
  { speaker: '１７番(有理紗)', bgKey: '255', text: 'はい！' },
  { speaker: '', bgKey: '255', text: 'こうして人知れず敗北したファタの勇者は、' },
  { speaker: '', bgKey: '255', text: 'マシナ国の一般兵へと堕ちてしまったのだった･･･' },
  { speaker: '', bgKey: '255', text: 'マシナ兵堕ちエンド' },
  { speaker: '', text: '— HD2 终 —', end: true },
];

export const HD3_LINES: AvdLineJSON[] = [
  { speaker: '機械音声', bgKey: '256', text: '反乱分子の捕獲に成功' },
  { speaker: '機械音声', bgKey: '256', text: 'これよりブレインウォッシュを開始します' },
  { speaker: '有理紗', bgKey: '256', text: 'ブレインウォッシュ…？' },
  { speaker: '有理紗', bgKey: '256', text: '洗脳ってこと？！マズイ！早く抜け出さないと…' },
  { speaker: '有理紗', bgKey: '256', text: 'ダメ拘束がきつくて抜け出せない…' },
  { speaker: 'ガウ', bgKey: '256', text: 'ガウも動けない…' },
  { speaker: '有理紗', bgKey: '256', text: 'ガウちゃん！！くっ…' },
  { speaker: '有理紗', bgKey: '260', text: '何！？これで洗脳する気！？' },
  { speaker: '機械音声', bgKey: '260', text: 'まずは記憶の消去を行います' },
  { speaker: '有理紗', bgKey: '260', text: '記憶の消去…？いやああああ離して！！消さないで！！！' },
  { speaker: 'ガウ', bgKey: '260', text: 'ガウ怖いよ…' },
  { speaker: '有理紗', bgKey: '261', text: 'あああああああ頭が痛いいいいいい' },
  { speaker: 'ガウ', bgKey: '261', text: 'ぎああああああ痛いやめてええええええ' },
  { speaker: '有理紗', bgKey: '261', text: '脳みそが焼ける焼けてるううううううう' },
  { speaker: '有理紗', bgKey: '261', text: '(ダメ、忘れないようにしないと！' },
  { speaker: '有理紗', bgKey: '261', text: ' 私の記憶消えないように思い出し続けないと！！)' },
  { speaker: '有理紗', bgKey: '262', text: 'ぐぎぎぎぎぎぎぎ' },
  { speaker: '', bgKey: '262', text: '脳が焼けるような痛みに必死に耐えようとする有理紗。' },
  { speaker: '有理紗', bgKey: '262', text: '(思い出さないと…私の名前、私の名前は…)' },
  { speaker: '有理紗', bgKey: '262', text: '(私の名前は･･････)' },
  { speaker: '有理紗', bgKey: '263', text: '(あれ？私の名前…)' },
  { speaker: '有理紗', bgKey: '263', text: '(私…私･･････)' },
  { speaker: '有理紗', bgKey: '263', text: '(私って…誰…？)' },
  { speaker: 'ガウ', bgKey: '263', text: '(ガウ…消えちゃうの…)' },
  { speaker: 'ガウ', bgKey: '264', text: '(■■消えたくない…)' },
  { speaker: 'ガウ', bgKey: '264', text: '(あれ？自分のことがわからない…)' },
  { speaker: '機械音声', bgKey: '265', text: '記憶消去完了' },
  { speaker: '機械音声', bgKey: '265', text: '感情の制御に移ります' },
  { speaker: '有理紗', bgKey: '266', text: '(ああ…気持ち良い…頭が真っ白になる…)' },
  { speaker: '', bgKey: '266', text: '先ほどまで脳が焼けるような痛みだったが、' },
  { speaker: '', bgKey: '266', text: '今は脳に走る電撃が心地よく感じている。' },
  { speaker: '', bgKey: '266', text: 'もう有理紗は何の思考も残っていなかった。' },
  { speaker: 'ガウ', bgKey: '266', text: '(気持ち良い…)' },
  { speaker: '', bgKey: '266', text: 'それはガウも一緒だった。' },
  { speaker: '機械音声', bgKey: '266', text: '感情消失確認' },
  { speaker: '機械音声', bgKey: '266', text: '最終工程へ移ります' },
  { speaker: '', bgKey: '266', text: '完全に無となっている有理紗とガウの中に' },
  { speaker: '', bgKey: '266', text: '１つの文章が浮かび上がる。' },
  { speaker: '', bgKey: '266', text: '『マシナ国に忠誠を』' },
  { speaker: '有理紗＆ガウ', bgKey: '266', text: 'マシナ国に…忠誠を…' },
  { speaker: '', bgKey: '266', text: '無意識に復唱する有理紗とガウ。' },
  { speaker: '', bgKey: '266', text: '『マシナ国に忠誠を』' },
  { speaker: '有理紗＆ガウ', bgKey: '266', text: 'マシナ国に忠誠を' },
  { speaker: '', bgKey: '266', text: '『マシナ国に忠誠を』' },
  { speaker: '有理紗＆ガウ', bgKey: '267', text: 'マシナ国に忠誠を！' },
  { speaker: '', bgKey: '267', text: '復唱するたびに有理紗とガウの中にマシナ国の情報が入って来る。' },
  { speaker: '有理紗', bgKey: '267', text: '(私はマシナ国に忠誠を誓う兵士…)' },
  { speaker: '有理紗', bgKey: '267', text: '(私はマシナ国のために戦うだけの存在…)' },
  { speaker: 'ガウ', bgKey: '267', text: '(■■…違う『ワタシ』…ワタシはマシナ国に忠誠を誓う兵士…)' },
  { speaker: '機械音声', bgKey: '257', text: 'ブレインウォッシュ完了' },
  { speaker: '機械音声', bgKey: '257', text: '拘束を解除します' },
  { speaker: '', bgKey: '258', text: 'まず洗脳装置が外される。' },
  { speaker: '有理紗＆ガウ', bgKey: '259', text: 'マシナ国に忠誠を！' },
  { speaker: '', bgKey: '259', text: '有理紗とガウにはもうマシナ国のことしか頭になかった。' },
  { speaker: '', bgKey: '259', text: 'こうして有理紗とガウは、' },
  { speaker: '', bgKey: '259', text: '一般兵として前線へと送られるのだった･･･' },
  { speaker: '', text: '— HD3 终 —', end: true },
];

export const HE1_LINES: AvdLineJSON[] = [
  { speaker: '', text: '一般兵となった有理紗は前線部隊にいた。' },
  { speaker: '全員', bgKey: '268', text: '「「「マシナ国に忠誠を」」」' },
  { speaker: '', bgKey: '268', text: '他の洗脳された女性たちと共にマシナ国への忠誠を叫ぶ' },
  { speaker: '', bgKey: '268', text: '有理紗とガウ。' },
  { speaker: 'ムノー上官', bgKey: '269', text: 'よし！次に俺に対しての挨拶！！' },
  { speaker: '全員', bgKey: '270', text: '「「「ムノー上官に忠誠を！！」」」' },
  { speaker: 'ムノー上官', bgKey: '270', text: '何度見ても凄い眺めだな…' },
  { speaker: 'ムノー上官', bgKey: '271', text: '前線に送られてきた兵士は俺の命令を何でも聞くから' },
  { speaker: 'ムノー上官', bgKey: '271', text: '好き放題できて最高だな' },
  { speaker: 'ムノー上官', bgKey: '271', text: '小茂田様には感謝しかない' },
  { speaker: 'ムノー上官', bgKey: '271', text: 'さて今日の相手は誰にしようかな･･･' },
  { speaker: '', bgKey: '271', text: 'スカートをたくし上げて静止している女性兵士を' },
  { speaker: '', bgKey: '271', text: '品定めするような目で見る上官。' },
  { speaker: 'ムノー上官', bgKey: '271', text: '獣人の子も良いが…' },
  { speaker: 'ムノー上官', bgKey: '272', text: '今日はお前だ！' },
  { speaker: '有理紗', bgKey: '273', text: 'はい、承知いたしました！！' },
  { speaker: 'ムノー上官', bgKey: '273', text: '何をされるかわかっているか？' },
  { speaker: '有理紗', bgKey: '273', text: 'はい！ムノー上官の性処理であります！' },
  { speaker: 'ムノー上官', bgKey: '273', text: '嫌じゃないのか？' },
  { speaker: '有理紗', bgKey: '273', text: 'そんなわけありません！' },
  { speaker: '有理紗', bgKey: '273', text: 'マシナ国のため、上官の命令に従うのは当然のこと' },
  { speaker: '有理紗', bgKey: '273', text: 'どんな命令でも喜んで従います！！' },
  { speaker: 'ムノー上官', bgKey: '273', text: 'ははは、本当に最高だな' },
  { speaker: 'ムノー上官', bgKey: '273', text: 'そういやお前、名前は？' },
  { speaker: '有理紗', bgKey: '273', text: '私のような一般兵に名前などありません！' },
  { speaker: '', bgKey: '273', text: '記憶消去をされている有理紗は、' },
  { speaker: '', bgKey: '273', text: '自分の名前を思い出すことすらできない。' },
  { speaker: '', bgKey: '273', text: 'だがそれはマシナ国のために必要のないこと。' },
  { speaker: '', bgKey: '273', text: '有理紗は自分の名前がわからないことを気にも留めていない。' },
  { speaker: 'ムノー上官', bgKey: '273', text: 'そうだったな･･･' },
  { speaker: 'ムノー上官', bgKey: '273', text: '反抗して一般兵にされた者は記憶消去処理をされて' },
  { speaker: 'ムノー上官', bgKey: '273', text: '名前も忘れてるんだったな･･･' },
  { speaker: 'ムノー上官', bgKey: '273', text: 'よし、お前は今日から１７番だ！' },
  { speaker: 'ムノー上官', bgKey: '273', text: '俺の１７番目の女という意味だ！' },
  { speaker: '１７番(有理紗)', bgKey: '273', text: 'わかりました！今日から私は１７番です！！' },
  { speaker: 'ムノー上官', bgKey: '273', text: 'そこの獣人の子は１８番だ！良いな？' },
  { speaker: '１８番(ガウ)', bgKey: '274', text: 'わかりました！今からワタシは１８番です！' },
  { speaker: 'ムノー上官', bgKey: '274', text: '良い返事だ！' },
  { speaker: 'ムノー上官', bgKey: '274', text: 'じゃあ１７番、後で俺の部屋に来なさい！' },
  { speaker: 'ムノー上官', bgKey: '274', text: '１８番も近いうちに頼むからな' },
  { speaker: '１７番(有理紗)', bgKey: '275', text: 'はい！' },
  { speaker: '１８番(ガウ)', bgKey: '275', text: 'はい！' },
  { speaker: '', bgKey: '275', text: 'こうして人知れず敗北したファタの勇者と獣人の子は、' },
  { speaker: '', bgKey: '275', text: 'マシナ国の一般兵へと堕ちてしまったのだった･･･' },
  { speaker: '', bgKey: '275', text: 'マシナ兵堕ちエンド２' },
  { speaker: '', text: '— HE1 终 —', end: true },
];
