import type { AvdLineJSON } from '../../components';

export const HC1_LINES: AvdLineJSON[] = [
  { speaker: '', bgKey: 'HC2-1', text: '两人移动到建筑物的阴影处。' },
  { speaker: '伊露', bgKey: 'HC2-1', text: '看吧，这样行了吧？' },
  { speaker: '', bgKey: 'HC2-1', text: '说着敞开衣服露出胸部的伊露。' },
  { speaker: '男人', bgKey: 'HC2-1', text: '哦哦、太棒了！！' },
  { speaker: '男人', bgKey: 'HC2-1', text: '啊啊、已经忍不住了' },
  { speaker: '', bgKey: 'HC2-2', text: '说着掏出勃起阴茎的男人。' },
  { speaker: '伊露', bgKey: 'HC2-2', text: '喂你在掏什么啊！！' },
  { speaker: '男人', bgKey: 'HC2-2', text: '我又不会碰你、拜托了、让我撸出来吧！' },
  { speaker: '伊露', bgKey: 'HC2-2', text: '要加钱的哦，可以吗？' },
  { speaker: '男人', bgKey: 'HC2-2', text: '当然！' },
  { speaker: '伊露', bgKey: 'HC2-3', text: '那就随便看个够吧' },
  { speaker: '男人', bgKey: 'HC2-3', text: '谢谢！\n还有…那个…' },
  { speaker: '男人', bgKey: 'HC2-3', text: '如果可以的话还想看看内裤…' },
  { speaker: '伊露', bgKey: 'HC2-4', text: '哈！？想看内裤，你是变态吗？！' },
  { speaker: '男人', bgKey: 'HC2-4', text: '别那么生气嘛！钱我会多给的！' },
  { speaker: '伊露', bgKey: 'HC2-4', text: '想看内裤你还真是变态呢' },
  { speaker: '伊露', bgKey: 'HC2-4', text: '算了、能拿到钱的话给你看看也行' },
  { speaker: '', bgKey: 'HC2-4', text: '由于思想逐渐被侵蚀，对于露出胸部这件事\n伊露已经没什么抵触了，\n但对于其他方面的认识还是老样子，\n所以对露出内裤还是感到抗拒。' },
  { speaker: '伊露', bgKey: 'HC2-5', text: '看吧、这样行了吧？' },
  { speaker: '', bgKey: 'HC2-5', text: '说着掀起裙子露出内裤的伊露。' },
  { speaker: '男人', bgKey: 'HC2-6', text: '啊啊太棒了！！' },
  { speaker: '男人', bgKey: 'HC2-6', text: '啊啊兴奋起来了…' },
  { speaker: '男人', bgKey: 'HC2-6', text: '真是太棒了…啊啊要射了' },
  { speaker: '', bgKey: 'HC2-7', text: '噗噗噗咻——' },
  { speaker: '伊露', bgKey: 'HC2-8', text: '呃…这就是精液…' },
  { speaker: '男人', bgKey: 'HC2-8', text: '哈啊…哈啊…真是太感谢了' },
  { speaker: '', bgKey: 'HC2-8', text: '整理好衣着的伊露。' },
  { speaker: '', text: '— HC1 终 —', end: true },
];
