import type { AvdLineJSON } from '../../components';

export const HD1_LINES: AvdLineJSON[] = [
  { speaker: '', text: '说着掏出勃起阴茎的欧派斯基。' },
  { speaker: '欧派斯基', bgKey: 'HD1-1', text: '来、用你的奶子夹住让我的鸡巴舒服一下' },
  { speaker: '伊露', bgKey: 'HD1-1', text: '明白了\n那我失礼了' },
  { speaker: '', bgKey: 'HD1-2', text: '伊露挪开衣服露出胸部，夹住欧派斯基的阴茎。' },
  { speaker: '伊露', bgKey: 'HD1-2', text: '怎么样欧派斯基大人？' },
  { speaker: '欧派斯基', bgKey: 'HD1-2', text: '不错就这样含进去让我舒服' },
  { speaker: '伊露', bgKey: 'HD1-2', text: '明白了' },
  { speaker: '', bgKey: 'HD1-3', text: '说着含住阴茎的伊露。' },
  { speaker: '', bgKey: 'HD1-4', text: '然后就这样动起来刺激阴茎。' },
  { speaker: '欧派斯基', bgKey: 'HD1-4', text: '哦哦不错、就这样继续' },
  { speaker: '伊露', bgKey: 'HD1-4', text: '(欧派斯基大人很开心…好幸福…)' },
  { speaker: '', bgKey: 'HD1-4', text: '伊露满脑子都是服从欧派斯基的喜悦。' },
  { speaker: '伊露', bgKey: 'HD1-4', text: '(还想…让他更舒服…)' },
  { speaker: '', bgKey: 'HD1-5', text: '热情上来了动作也变得更加激烈。' },
  { speaker: '欧派斯基', bgKey: 'HD1-5', text: '啊啊真不错…\n差不多要射了' },
  { speaker: '欧派斯基', bgKey: 'HD1-5', text: '啊啊射了' },
  { speaker: '', bgKey: 'HD1-6', text: '噗噗噗咻——' },
  { speaker: '伊露', bgKey: 'HD1-7', text: '嗯咕' },
  { speaker: '欧派斯基', bgKey: 'HD1-7', text: '全部喝掉' },
  { speaker: '伊露', bgKey: 'HD1-7', text: '咕嘟咕嘟咕嘟…' },
  { speaker: '', bgKey: 'HD1-7', text: '伊露服从命令喝干了射出的精液。' },
  { speaker: '伊露', bgKey: 'HD1-8', text: '噗哈…喝完了…' },
  { speaker: '欧派斯基', bgKey: 'HD1-9', text: '真乖' },
  { speaker: '伊露', bgKey: 'HD1-9', text: '那是当然的、因为我是欧派斯基大人的奴隶啊♡' },
  { speaker: '', bgKey: 'HD1-9', text: '那表情看起来非常幸福…' },
  { speaker: '', text: '— HD1 终 —', end: true },
];
