import type { AvdLineJSON } from '../../components';

export const HD3_LINES: AvdLineJSON[] = [
  { speaker: '', bgKey: 'HD3-1', text: '啪嗒啪嗒啪嗒啪嗒' },
  { speaker: '伊露', bgKey: 'HD3-1', text: '啊啊欧派斯基大人\n魔术协会的人们的洗脑已经完成了' },
  { speaker: '伊露', bgKey: 'HD3-1', text: '贫乳的孩子当女仆、其他人作为魔力容器' },
  { speaker: '欧派斯基', bgKey: 'HD3-1', text: '辛苦了\n对洗脑前同事没有抵触吗？' },
  { speaker: '伊露', bgKey: 'HD3-1', text: '怎么可能\n那些想要威胁欧派斯基大人国家的人\n我才不管他们怎么样呢' },
  { speaker: '欧派斯基', bgKey: 'HD3-1', text: '伊露真是好孩子\n而且能同时对付那么多魔术师并取胜\n真是个优秀的魔术师啊' },
  { speaker: '伊露', bgKey: 'HD3-1', text: '哪里称得上优秀\n我只是拼命想要保护欧派斯基大人而已' },
  { speaker: '欧派斯基', bgKey: 'HD3-1', text: '你对我的忠诚心真是了不起呢' },
  { speaker: '伊露', bgKey: 'HD3-2', text: '当然！我可是欧派斯基大人最棒的女仆♡' },
  { speaker: '', bgKey: 'HD3-2', text: '啪嗒啪嗒啪嗒啪嗒\n撞击声回响着。' },
  { speaker: '伊露', bgKey: 'HD3-2', text: '嗯啊…怎么样欧派斯基大人、舒服吗？' },
  { speaker: '欧派斯基', bgKey: 'HD3-2', text: '啊啊、不错\n伊露、和你做爱多少次都不会腻' },
  { speaker: '伊露', bgKey: 'HD3-2', text: '太高兴了欧派斯基大人♡' },
  { speaker: '伊露', bgKey: 'HD3-2', text: '请今后也一直使用我' },
  { speaker: '欧派斯基', bgKey: 'HD3-2', text: '当然啦、以后也要一直侍奉我哦' },
  { speaker: '伊露', bgKey: 'HD3-3', text: '是的！\n从今以后永远永远、侍奉欧派斯基大人♡' },
  { speaker: '欧派斯基', bgKey: 'HD3-3', text: '真高兴啊伊露' },
  { speaker: '欧派斯基', bgKey: 'HD3-3', text: '啊啊差不多要射了' },
  { speaker: '伊露', bgKey: 'HD3-3', text: '我也要去了' },
  { speaker: '欧派斯基', bgKey: 'HD3-3', text: '啊啊射了' },
  { speaker: '', bgKey: 'HD3-4', text: '噗噗噗咻' },
  { speaker: '伊露', bgKey: 'HD3-5', text: '啊啊…欧派斯基大人的有这么多…' },
  { speaker: '欧派斯基', bgKey: 'HD3-5', text: '今后也多多关照了' },
  { speaker: '伊露', bgKey: 'HD3-6', text: '是的、欧派斯基大人♡' },
  { speaker: '', bgKey: 'HD3-6', text: '伊露今后也将作为欧派斯基的近侍生活下去。' },
  { speaker: '', bgKey: 'HD3-6', text: '欧派斯基结局' },
  { speaker: '', text: '— HD3 终 —', end: true },
];
