import type { AvdLineJSON, AvdScriptJSON } from '../../components';

// Converted from CommonEvents.json event 60 (HE1洗脳)
// speaker="" lines are narration (no name shown)
export const HE1_LINES: AvdLineJSON[] = [
  { speaker: '', text: '伊露意外地败给了欧派斯基，被抓住后\n束缚在装置上。' },
  { speaker: '伊露', bgKey: 'HE1-1', text: '你打算把我怎么样！？' },
  { speaker: '欧派斯基', text: '让你和你来救的那个女人变成一样的状态' },
  { speaker: '伊露', text: '一样…' },
  { speaker: '', text: '她想起那个像是失去了所有感情的协会会员的样子。' },
  { speaker: '伊露', text: '不要！！我不想变成那样！！' },
  { speaker: '欧派斯基', text: '不行，像你这样会反抗我的危险分子必须清除掉' },
  { speaker: '欧派斯基', text: '不过，和那个女人不同，你的身体很棒' },
  { speaker: '欧派斯基', text: '就算抹去感情之后，那副身体我也会好好使用的' },
  { speaker: '伊露', text: '不要！我才不要被你使用啊啊啊' },
  { speaker: '欧派斯基', text: '那开始了！' },
  { speaker: '', bgKey: 'HE1-2', text: '装置启动。' },
  { speaker: '伊露', text: '啊啊啊啊啊啊啊停下！停下————！！！' },
  { speaker: '欧派斯基', text: '首先让我把你残存的魔力全部抽走' },
  { speaker: '欧派斯基', text: '记忆应该也会一起被抽走，\n反正对你今后来说也是不需要的东西，没问题吧' },
  { speaker: '伊露', text: '啊啊啊啊啊不要啊啊啊被吸走了\n魔力被吸走了啊啊啊' },
  { speaker: '伊露', text: '啊啊什么…从我里面有什么…\n不只是魔力，好像还有其他东西也被吸走了…' },
  { speaker: '伊露', text: '这就是记忆被吸走的感觉…\n不要啊但我不知道什么东西在消失啊' },
  { speaker: '欧派斯基', text: '不错不错就是这样\n记忆之后，人格也要抽出来消除掉哦' },
  { speaker: '伊露', bgKey: 'HE1-3', text: '不要啊啊啊啊不要消除我啊啊啊啊' },
  { speaker: '伊露', text: '求求你了欧派斯基大人！！\n我再也不反抗了请不要消除我啊啊啊啊！！！' },
  { speaker: '欧派斯基', text: '不——行' },
  { speaker: '欧派斯基', text: '因为只要消除人格你就会自动不反抗我了，\n我没理由留下可能被反抗的隐患吧' },
  { speaker: '伊露', text: '不要啊啊啊啊啊啊啊啊' },
  { speaker: '伊露', text: '啊啊消失了好消失好啊啊啊' },
  { speaker: '', bgKey: 'HE1-4', text: '身体猛地一颤。' },
  { speaker: '伊露', bgKey: 'HE1-5', text: '啊呀…啊呀…不要啊…我…我…' },
  { speaker: '伊露', bgKey: 'HE1-5^', text: '咦…什么都想不起来了…我是谁…到底是谁啊啊啊' },
  { speaker: '伊露', text: '我为什么在经历这种事情啊啊啊' },
  { speaker: '伊露', text: '谁来告诉我——' },
  { speaker: '欧派斯基', text: '看来失去记忆后混乱了呢' },
  { speaker: '欧派斯基', text: '放心吧，你那人格也马上就会消失的' },
  { speaker: '伊露', text: '诶我要消失了吗？' },
  { speaker: '伊露', bgKey: 'HE1-6', text: '不不不要啊啊啊啊我不想消失啊啊啊\n谁来救救我啊啊啊啊啊啊' },
  { speaker: '欧派斯基', text: '好了终结吧！' },
  { speaker: '伊露', text: '啊啊啊啊啊我被吸走啊啊啊啊啊啊\n啊啊啊啊啊啊啊啊' },
  { speaker: '', bgKey: 'HE1-7', text: '一颤一颤\n伊露的身体做出像是达到高潮的反应。' },
  { speaker: '', bgKey: 'HE1-8', text: '与此同时装置停止。' },
  { speaker: '欧派斯基', text: '完成了吗' },
  { speaker: '', bgKey: 'HE1-9', text: '取下装置的护目镜后，伊露眼神空洞。' },
  { speaker: '欧派斯基', text: '看来记忆和人格都完全失去了\n接下来只要注入对我顺从的最低限度的感情就完成了' },
  { speaker: '', bgKey: 'HE1-10', text: '说着护目镜再次被戴上。' },
  { speaker: '欧派斯基', text: '好了接下来要投入对我有利的记忆和感情了' },
  { speaker: '', bgKey: 'HE1-11', text: '装置再次启动。' },
  { speaker: '', text: '这次是魔力流入伊露体内。' },
  { speaker: '伊露', text: '啊啊…欧派斯基大人…我的主人…\n发誓绝对忠诚的主人…' },
  { speaker: '', text: '对欧派斯基有利的感情被植入伊露体内…' },
  { speaker: '', bgKey: 'HE1-10', text: '然后装置停止。' },
  { speaker: '欧派斯基', text: '这样就好了吧' },
  { speaker: '', bgKey: 'HE1-13', text: '头盔被取下。' },
  { speaker: '欧派斯基', text: '那么你是谁呢？' },
  { speaker: '伊露', bgKey: 'HE1-14', text: '我是主人忠实的奴隶' },
  { speaker: '伊露', text: '名字…不知道' },
  { speaker: '欧派斯基', text: '这样啊，连名字都忘了啊' },
  { speaker: '欧派斯基', text: '算了\n反正你大部分时间都要在这里作为魔力容器度过\n几乎没有被我召唤的机会' },
  { speaker: '欧派斯基', text: '不过，今天还是会用你的\n来，跟我到房间来' },
  { speaker: '伊露', text: '是，主人' },
  { speaker: '', text: '— HE1 洗脑结局 终 —', end: true },
];

export const HE1_SCRIPT: AvdScriptJSON = {
  meta: { boxWidth: 900, boxHeight: 240, textSize: 22, nameSize: 20 },
  lines: HE1_LINES,
};
