import type { AvdLineJSON, AvdScriptJSON } from '../../components';

export const T3_LINES: AvdLineJSON[] = [
  { speaker: '', bgKey: 'z_e', text: '说着脱下衣服的伊露。' },
  { speaker: '欧派斯基', text: '哦哦，长了一对好胸啊' },
  { speaker: '伊露', bgKey: 'T3-1', text: '(啊啊…欧派斯基大人夸我的胸了)' },
  { speaker: '伊露', text: '(好开心…开心到光是这样就快要去了)' },
  { speaker: '欧派斯基', text: '难得的机会，让我揉一下吧' },
  { speaker: '伊露', text: '(诶…现在被欧派斯基大人碰到的话我…)' },
  { speaker: '欧派斯基', bgKey: 'T3-2', text: '哦哦…形状真好' },
  { speaker: '', bgKey: 'T3-3', text: '伊露被捏住乳头。' },
  { speaker: '伊露', text: '啊嗯欧派斯基大人、啊啊' },
  { speaker: '', bgKey: 'T3-4', text: '一颤一颤\n伊露达到高潮。' },
  { speaker: '欧派斯基', bgKey: 'T3-5', text: '哦，抱歉让你去了吗' },
  { speaker: '伊露', bgKey: 'z_e2', text: '非常抱歉欧派斯基大人\n一想到是被欧派斯基大人触碰着，\n就光是那样就开心得不行…' },
  { speaker: '欧派斯基', text: '没关系，这说明你那么想我了对吧？' },
  { speaker: '伊露', bgKey: 'z_ht', text: '是的\n我一直都盼望着被欧派斯基大人抚摸' },
  { speaker: '伊露', text: '真的被抚摸的日子到来\n我开心得快要不行了' },
  { speaker: '欧派斯基', text: '以后还会摸很多次的\n你得学会忍耐住马上就去才行' },
  { speaker: '欧派斯基', text: '不过，别忘了对我的感情' },
  { speaker: '伊露', text: '当然！\n对欧派斯基大人的感情怎么可能消失！！' },
  { speaker: '欧派斯基', text: '那就好，来继续换衣服吧' },
  { speaker: '伊露', text: '是欧派斯基大人' },
  { speaker: '', bgKey: 'm0_e', text: '然后伊露换上了女仆装。' },
  { speaker: '欧派斯基', text: '最后还得戴上这个' },
  { speaker: '', bgKey: 'm_e', text: '然后脖子上被戴上了金色项圈。' },
  { speaker: '伊露', bgKey: 'm_e2', text: '这是金色项圈！！' },
  { speaker: '欧派斯基', text: '你知道？' },
  { speaker: '伊露', text: '是的，\n只有被欧派斯基大人认可的人才能戴上的项圈' },
  { speaker: '伊露', text: '据说戴上这个项圈的人\n在这个国家拥有第二大的权力' },
  { speaker: '欧派斯基', text: '没错，你知道得很清楚嘛' },
  { speaker: '欧派斯基', text: '市面上流通的普通项圈是用来赋予\n对我的临时奴隶契约的，但这个项圈不同' },
  { speaker: '欧派斯基', text: '它可以结成更牢固的奴隶契约\n而且这个项圈是这个国家地位第二高的证明\n在这个国家你不需要服从除了我以外的任何人，做什么都可以' },
  { speaker: '伊露', text: '这么棒的东西，我真的可以拥有吗？' },
  { speaker: '欧派斯基', text: '当然，你外表不错实力也无可挑剔\n我觉得你可以和我一起把国家变得更好' },
  { speaker: '伊露', bgKey: 'm_e3', text: '欧派斯基大人♡' },
  { speaker: '欧派斯基', text: '来，缔结奴隶契约吧\n我会往项圈里注入魔力来契约，你别动' },
  { speaker: '伊露', text: '那就订下更强大的契约吧！\n光靠项圈的话摘下来时有可能会解除契约\n不仅项圈，连我自身也一起契约吧' },
  { speaker: '欧派斯基', text: '可以吗？' },
  { speaker: '伊露', text: '当然！\n为了今后万一我也不会违背欧派斯基大人，\n让我们订下我所知的最强的契约吧' },
  { speaker: '欧派斯基', text: '那不错\n那就先把项圈的契约快速搞定' },
  { speaker: '', text: '说着往项圈里注入魔力，完成了奴隶契约。' },
  { speaker: '伊露', text: '这样我就成为欧派斯基大人的奴隶了呢\n不过，正戏才刚开始！' },
  { speaker: '伊露', text: '来，让我们缔结将我身心全部\n献给欧派斯基大人的奴隶契约吧' },
  { speaker: '欧派斯基', text: '那个契约缔结后会变成怎样？' },
  { speaker: '伊露', text: '会变得无法产生\n违背主人欧派斯基大人的意愿' },
  { speaker: '伊露', text: '当然也无法违抗主人的命令\n而且根据命令，甚至可以改写心灵' },
  { speaker: '欧派斯基', text: '什么，连心都能改写' },
  { speaker: '伊露', text: '如果我无法成为让欧派斯基大人满意的奴隶时\n请不要客气地改写我' },
  { speaker: '欧派斯基', text: '我觉得除非发生什么大事，否则不会做到那一步' },
  { speaker: '伊露', text: '欧派斯基大人真是温柔呢' },
  { speaker: '伊露', text: '总之，我将不再拥有人权\n一切全凭欧派斯基大人心意' },
  { speaker: '欧派斯基', text: '是吗，你想缔结那么单方面的奴隶契约啊' },
  { speaker: '伊露', text: '是的，难得能被欧派斯基大人支配\n我觉得不做到这个程度是不行的' },
  { speaker: '欧派斯基', text: '是吗，为我做到这种地步…我非常高兴\n那就缔结契约吧' },
  { speaker: '', text: '伊露将契约的方法告诉了欧派斯基。' },
  { speaker: '伊露', bgKey: 'm_hy', text: '(啊啊…欧派斯基大人\n 我的一切都是欧派斯基大人的东西…)' },
  { speaker: '', text: '然后契约完成。' },
  { speaker: '伊露', bgKey: 'm_ht3', text: '这样一来我一生都是欧派斯基大人的东西了\n今后请多多指教' },
  { speaker: '', text: '— T3 性骚扰 终 —', end: true },
];

export const T3_SCRIPT: AvdScriptJSON = {
  meta: { boxWidth: 900, boxHeight: 240, textSize: 22, nameSize: 20 },
  lines: T3_LINES,
};
